package com.comerzzia.bricodepot.backoffice.persistence.ventas.informetto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class InformeTtoVentasExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public InformeTtoVentasExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("UID_ACTIVIDAD is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("UID_ACTIVIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("UID_ACTIVIDAD >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("UID_ACTIVIDAD <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("UID_ACTIVIDAD like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("UID_ACTIVIDAD not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("FECHA is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterionForJDBCDate("FECHA >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterionForJDBCDate("FECHA <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterionForJDBCDate("FECHA in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterionForJDBCDate("FECHA not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FECHA between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FECHA not between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNull() {
            addCriterion("CODALM is null");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNotNull() {
            addCriterion("CODALM is not null");
            return (Criteria) this;
        }

        public Criteria andCodalmEqualTo(String value) {
            addCriterion("CODALM =", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotEqualTo(String value) {
            addCriterion("CODALM <>", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThan(String value) {
            addCriterion("CODALM >", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThanOrEqualTo(String value) {
            addCriterion("CODALM >=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThan(String value) {
            addCriterion("CODALM <", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThanOrEqualTo(String value) {
            addCriterion("CODALM <=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLike(String value) {
            addCriterion("CODALM like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotLike(String value) {
            addCriterion("CODALM not like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmIn(List<String> values) {
            addCriterion("CODALM in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotIn(List<String> values) {
            addCriterion("CODALM not in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmBetween(String value1, String value2) {
            addCriterion("CODALM between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotBetween(String value1, String value2) {
            addCriterion("CODALM not between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodcajaIsNull() {
            addCriterion("CODCAJA is null");
            return (Criteria) this;
        }

        public Criteria andCodcajaIsNotNull() {
            addCriterion("CODCAJA is not null");
            return (Criteria) this;
        }

        public Criteria andCodcajaEqualTo(String value) {
            addCriterion("CODCAJA =", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotEqualTo(String value) {
            addCriterion("CODCAJA <>", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaGreaterThan(String value) {
            addCriterion("CODCAJA >", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaGreaterThanOrEqualTo(String value) {
            addCriterion("CODCAJA >=", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaLessThan(String value) {
            addCriterion("CODCAJA <", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaLessThanOrEqualTo(String value) {
            addCriterion("CODCAJA <=", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaLike(String value) {
            addCriterion("CODCAJA like", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotLike(String value) {
            addCriterion("CODCAJA not like", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaIn(List<String> values) {
            addCriterion("CODCAJA in", values, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotIn(List<String> values) {
            addCriterion("CODCAJA not in", values, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaBetween(String value1, String value2) {
            addCriterion("CODCAJA between", value1, value2, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotBetween(String value1, String value2) {
            addCriterion("CODCAJA not between", value1, value2, "codcaja");
            return (Criteria) this;
        }

        public Criteria andKpiIsNull() {
            addCriterion("KPI is null");
            return (Criteria) this;
        }

        public Criteria andKpiIsNotNull() {
            addCriterion("KPI is not null");
            return (Criteria) this;
        }

        public Criteria andKpiEqualTo(BigDecimal value) {
            addCriterion("KPI =", value, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiNotEqualTo(BigDecimal value) {
            addCriterion("KPI <>", value, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiGreaterThan(BigDecimal value) {
            addCriterion("KPI >", value, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("KPI >=", value, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiLessThan(BigDecimal value) {
            addCriterion("KPI <", value, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiLessThanOrEqualTo(BigDecimal value) {
            addCriterion("KPI <=", value, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiIn(List<BigDecimal> values) {
            addCriterion("KPI in", values, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiNotIn(List<BigDecimal> values) {
            addCriterion("KPI not in", values, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("KPI between", value1, value2, "kpi");
            return (Criteria) this;
        }

        public Criteria andKpiNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("KPI not between", value1, value2, "kpi");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaIsNull() {
            addCriterion("CIFRA_DE_VENTA is null");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaIsNotNull() {
            addCriterion("CIFRA_DE_VENTA is not null");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaEqualTo(BigDecimal value) {
            addCriterion("CIFRA_DE_VENTA =", value, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaNotEqualTo(BigDecimal value) {
            addCriterion("CIFRA_DE_VENTA <>", value, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaGreaterThan(BigDecimal value) {
            addCriterion("CIFRA_DE_VENTA >", value, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CIFRA_DE_VENTA >=", value, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaLessThan(BigDecimal value) {
            addCriterion("CIFRA_DE_VENTA <", value, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CIFRA_DE_VENTA <=", value, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaIn(List<BigDecimal> values) {
            addCriterion("CIFRA_DE_VENTA in", values, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaNotIn(List<BigDecimal> values) {
            addCriterion("CIFRA_DE_VENTA not in", values, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CIFRA_DE_VENTA between", value1, value2, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andCifraDeVentaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CIFRA_DE_VENTA not between", value1, value2, "cifraDeVenta");
            return (Criteria) this;
        }

        public Criteria andSiCofreIsNull() {
            addCriterion("SI_COFRE is null");
            return (Criteria) this;
        }

        public Criteria andSiCofreIsNotNull() {
            addCriterion("SI_COFRE is not null");
            return (Criteria) this;
        }

        public Criteria andSiCofreEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE =", value, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreNotEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE <>", value, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreGreaterThan(BigDecimal value) {
            addCriterion("SI_COFRE >", value, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE >=", value, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreLessThan(BigDecimal value) {
            addCriterion("SI_COFRE <", value, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE <=", value, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreIn(List<BigDecimal> values) {
            addCriterion("SI_COFRE in", values, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreNotIn(List<BigDecimal> values) {
            addCriterion("SI_COFRE not in", values, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SI_COFRE between", value1, value2, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSiCofreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SI_COFRE not between", value1, value2, "siCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreIsNull() {
            addCriterion("SF_COFRE is null");
            return (Criteria) this;
        }

        public Criteria andSfCofreIsNotNull() {
            addCriterion("SF_COFRE is not null");
            return (Criteria) this;
        }

        public Criteria andSfCofreEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE =", value, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreNotEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE <>", value, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreGreaterThan(BigDecimal value) {
            addCriterion("SF_COFRE >", value, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE >=", value, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreLessThan(BigDecimal value) {
            addCriterion("SF_COFRE <", value, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE <=", value, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreIn(List<BigDecimal> values) {
            addCriterion("SF_COFRE in", values, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreNotIn(List<BigDecimal> values) {
            addCriterion("SF_COFRE not in", values, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SF_COFRE between", value1, value2, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andSfCofreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SF_COFRE not between", value1, value2, "sfCofre");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaIsNull() {
            addCriterion("COMPRA_DE_MONEDA is null");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaIsNotNull() {
            addCriterion("COMPRA_DE_MONEDA is not null");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaEqualTo(BigDecimal value) {
            addCriterion("COMPRA_DE_MONEDA =", value, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaNotEqualTo(BigDecimal value) {
            addCriterion("COMPRA_DE_MONEDA <>", value, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaGreaterThan(BigDecimal value) {
            addCriterion("COMPRA_DE_MONEDA >", value, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COMPRA_DE_MONEDA >=", value, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaLessThan(BigDecimal value) {
            addCriterion("COMPRA_DE_MONEDA <", value, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COMPRA_DE_MONEDA <=", value, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaIn(List<BigDecimal> values) {
            addCriterion("COMPRA_DE_MONEDA in", values, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaNotIn(List<BigDecimal> values) {
            addCriterion("COMPRA_DE_MONEDA not in", values, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMPRA_DE_MONEDA between", value1, value2, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andCompraDeMonedaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMPRA_DE_MONEDA not between", value1, value2, "compraDeMoneda");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasIsNull() {
            addCriterion("SI_COFRE_RETIRADAS is null");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasIsNotNull() {
            addCriterion("SI_COFRE_RETIRADAS is not null");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE_RETIRADAS =", value, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasNotEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE_RETIRADAS <>", value, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasGreaterThan(BigDecimal value) {
            addCriterion("SI_COFRE_RETIRADAS >", value, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE_RETIRADAS >=", value, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasLessThan(BigDecimal value) {
            addCriterion("SI_COFRE_RETIRADAS <", value, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SI_COFRE_RETIRADAS <=", value, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasIn(List<BigDecimal> values) {
            addCriterion("SI_COFRE_RETIRADAS in", values, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasNotIn(List<BigDecimal> values) {
            addCriterion("SI_COFRE_RETIRADAS not in", values, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SI_COFRE_RETIRADAS between", value1, value2, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSiCofreRetiradasNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SI_COFRE_RETIRADAS not between", value1, value2, "siCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasIsNull() {
            addCriterion("SF_COFRE_RETIRADAS is null");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasIsNotNull() {
            addCriterion("SF_COFRE_RETIRADAS is not null");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE_RETIRADAS =", value, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasNotEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE_RETIRADAS <>", value, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasGreaterThan(BigDecimal value) {
            addCriterion("SF_COFRE_RETIRADAS >", value, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE_RETIRADAS >=", value, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasLessThan(BigDecimal value) {
            addCriterion("SF_COFRE_RETIRADAS <", value, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SF_COFRE_RETIRADAS <=", value, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasIn(List<BigDecimal> values) {
            addCriterion("SF_COFRE_RETIRADAS in", values, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasNotIn(List<BigDecimal> values) {
            addCriterion("SF_COFRE_RETIRADAS not in", values, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SF_COFRE_RETIRADAS between", value1, value2, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andSfCofreRetiradasNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SF_COFRE_RETIRADAS not between", value1, value2, "sfCofreRetiradas");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosIsNull() {
            addCriterion("ANTICIPOS_PAGADOS is null");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosIsNotNull() {
            addCriterion("ANTICIPOS_PAGADOS is not null");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_PAGADOS =", value, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosNotEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_PAGADOS <>", value, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosGreaterThan(BigDecimal value) {
            addCriterion("ANTICIPOS_PAGADOS >", value, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_PAGADOS >=", value, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosLessThan(BigDecimal value) {
            addCriterion("ANTICIPOS_PAGADOS <", value, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_PAGADOS <=", value, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosIn(List<BigDecimal> values) {
            addCriterion("ANTICIPOS_PAGADOS in", values, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosNotIn(List<BigDecimal> values) {
            addCriterion("ANTICIPOS_PAGADOS not in", values, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ANTICIPOS_PAGADOS between", value1, value2, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposPagadosNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ANTICIPOS_PAGADOS not between", value1, value2, "anticiposPagados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosIsNull() {
            addCriterion("ANTICIPOS_DESCONTADOS is null");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosIsNotNull() {
            addCriterion("ANTICIPOS_DESCONTADOS is not null");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_DESCONTADOS =", value, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosNotEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_DESCONTADOS <>", value, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosGreaterThan(BigDecimal value) {
            addCriterion("ANTICIPOS_DESCONTADOS >", value, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_DESCONTADOS >=", value, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosLessThan(BigDecimal value) {
            addCriterion("ANTICIPOS_DESCONTADOS <", value, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ANTICIPOS_DESCONTADOS <=", value, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosIn(List<BigDecimal> values) {
            addCriterion("ANTICIPOS_DESCONTADOS in", values, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosNotIn(List<BigDecimal> values) {
            addCriterion("ANTICIPOS_DESCONTADOS not in", values, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ANTICIPOS_DESCONTADOS between", value1, value2, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andAnticiposDescontadosNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ANTICIPOS_DESCONTADOS not between", value1, value2, "anticiposDescontados");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorIsNull() {
            addCriterion("PAGO_A_PROVEEDOR is null");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorIsNotNull() {
            addCriterion("PAGO_A_PROVEEDOR is not null");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorEqualTo(BigDecimal value) {
            addCriterion("PAGO_A_PROVEEDOR =", value, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorNotEqualTo(BigDecimal value) {
            addCriterion("PAGO_A_PROVEEDOR <>", value, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorGreaterThan(BigDecimal value) {
            addCriterion("PAGO_A_PROVEEDOR >", value, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAGO_A_PROVEEDOR >=", value, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorLessThan(BigDecimal value) {
            addCriterion("PAGO_A_PROVEEDOR <", value, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAGO_A_PROVEEDOR <=", value, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorIn(List<BigDecimal> values) {
            addCriterion("PAGO_A_PROVEEDOR in", values, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorNotIn(List<BigDecimal> values) {
            addCriterion("PAGO_A_PROVEEDOR not in", values, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAGO_A_PROVEEDOR between", value1, value2, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andPagoAProveedorNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAGO_A_PROVEEDOR not between", value1, value2, "pagoAProveedor");
            return (Criteria) this;
        }

        public Criteria andRetiradaIsNull() {
            addCriterion("RETIRADA is null");
            return (Criteria) this;
        }

        public Criteria andRetiradaIsNotNull() {
            addCriterion("RETIRADA is not null");
            return (Criteria) this;
        }

        public Criteria andRetiradaEqualTo(BigDecimal value) {
            addCriterion("RETIRADA =", value, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaNotEqualTo(BigDecimal value) {
            addCriterion("RETIRADA <>", value, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaGreaterThan(BigDecimal value) {
            addCriterion("RETIRADA >", value, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RETIRADA >=", value, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaLessThan(BigDecimal value) {
            addCriterion("RETIRADA <", value, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RETIRADA <=", value, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaIn(List<BigDecimal> values) {
            addCriterion("RETIRADA in", values, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaNotIn(List<BigDecimal> values) {
            addCriterion("RETIRADA not in", values, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RETIRADA between", value1, value2, "retirada");
            return (Criteria) this;
        }

        public Criteria andRetiradaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RETIRADA not between", value1, value2, "retirada");
            return (Criteria) this;
        }

        public Criteria andEfectivoIsNull() {
            addCriterion("EFECTIVO is null");
            return (Criteria) this;
        }

        public Criteria andEfectivoIsNotNull() {
            addCriterion("EFECTIVO is not null");
            return (Criteria) this;
        }

        public Criteria andEfectivoEqualTo(BigDecimal value) {
            addCriterion("EFECTIVO =", value, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoNotEqualTo(BigDecimal value) {
            addCriterion("EFECTIVO <>", value, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoGreaterThan(BigDecimal value) {
            addCriterion("EFECTIVO >", value, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EFECTIVO >=", value, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoLessThan(BigDecimal value) {
            addCriterion("EFECTIVO <", value, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EFECTIVO <=", value, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoIn(List<BigDecimal> values) {
            addCriterion("EFECTIVO in", values, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoNotIn(List<BigDecimal> values) {
            addCriterion("EFECTIVO not in", values, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EFECTIVO between", value1, value2, "efectivo");
            return (Criteria) this;
        }

        public Criteria andEfectivoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EFECTIVO not between", value1, value2, "efectivo");
            return (Criteria) this;
        }

        public Criteria andTarjetaIsNull() {
            addCriterion("TARJETA is null");
            return (Criteria) this;
        }

        public Criteria andTarjetaIsNotNull() {
            addCriterion("TARJETA is not null");
            return (Criteria) this;
        }

        public Criteria andTarjetaEqualTo(BigDecimal value) {
            addCriterion("TARJETA =", value, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaNotEqualTo(BigDecimal value) {
            addCriterion("TARJETA <>", value, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaGreaterThan(BigDecimal value) {
            addCriterion("TARJETA >", value, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TARJETA >=", value, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaLessThan(BigDecimal value) {
            addCriterion("TARJETA <", value, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TARJETA <=", value, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaIn(List<BigDecimal> values) {
            addCriterion("TARJETA in", values, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaNotIn(List<BigDecimal> values) {
            addCriterion("TARJETA not in", values, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TARJETA between", value1, value2, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TARJETA not between", value1, value2, "tarjeta");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualIsNull() {
            addCriterion("TARJETA_MANUAL is null");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualIsNotNull() {
            addCriterion("TARJETA_MANUAL is not null");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualEqualTo(BigDecimal value) {
            addCriterion("TARJETA_MANUAL =", value, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualNotEqualTo(BigDecimal value) {
            addCriterion("TARJETA_MANUAL <>", value, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualGreaterThan(BigDecimal value) {
            addCriterion("TARJETA_MANUAL >", value, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TARJETA_MANUAL >=", value, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualLessThan(BigDecimal value) {
            addCriterion("TARJETA_MANUAL <", value, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TARJETA_MANUAL <=", value, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualIn(List<BigDecimal> values) {
            addCriterion("TARJETA_MANUAL in", values, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualNotIn(List<BigDecimal> values) {
            addCriterion("TARJETA_MANUAL not in", values, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TARJETA_MANUAL between", value1, value2, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andTarjetaManualNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TARJETA_MANUAL not between", value1, value2, "tarjetaManual");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionIsNull() {
            addCriterion("ES_FINANCIACION is null");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionIsNotNull() {
            addCriterion("ES_FINANCIACION is not null");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionEqualTo(BigDecimal value) {
            addCriterion("ES_FINANCIACION =", value, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionNotEqualTo(BigDecimal value) {
            addCriterion("ES_FINANCIACION <>", value, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionGreaterThan(BigDecimal value) {
            addCriterion("ES_FINANCIACION >", value, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ES_FINANCIACION >=", value, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionLessThan(BigDecimal value) {
            addCriterion("ES_FINANCIACION <", value, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ES_FINANCIACION <=", value, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionIn(List<BigDecimal> values) {
            addCriterion("ES_FINANCIACION in", values, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionNotIn(List<BigDecimal> values) {
            addCriterion("ES_FINANCIACION not in", values, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ES_FINANCIACION between", value1, value2, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andEsFinanciacionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ES_FINANCIACION not between", value1, value2, "esFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionIsNull() {
            addCriterion("PT_FINANCIACION is null");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionIsNotNull() {
            addCriterion("PT_FINANCIACION is not null");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionEqualTo(BigDecimal value) {
            addCriterion("PT_FINANCIACION =", value, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionNotEqualTo(BigDecimal value) {
            addCriterion("PT_FINANCIACION <>", value, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionGreaterThan(BigDecimal value) {
            addCriterion("PT_FINANCIACION >", value, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PT_FINANCIACION >=", value, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionLessThan(BigDecimal value) {
            addCriterion("PT_FINANCIACION <", value, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PT_FINANCIACION <=", value, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionIn(List<BigDecimal> values) {
            addCriterion("PT_FINANCIACION in", values, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionNotIn(List<BigDecimal> values) {
            addCriterion("PT_FINANCIACION not in", values, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PT_FINANCIACION between", value1, value2, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andPtFinanciacionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PT_FINANCIACION not between", value1, value2, "ptFinanciacion");
            return (Criteria) this;
        }

        public Criteria andTransferenciaIsNotNull() {
            addCriterion("TRANSFERENCIA is not null");
            return (Criteria) this;
        }

        public Criteria andTransferenciaEqualTo(BigDecimal value) {
            addCriterion("TRANSFERENCIA =", value, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaNotEqualTo(BigDecimal value) {
            addCriterion("TRANSFERENCIA <>", value, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaGreaterThan(BigDecimal value) {
            addCriterion("TRANSFERENCIA >", value, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANSFERENCIA >=", value, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaLessThan(BigDecimal value) {
            addCriterion("TRANSFERENCIA <", value, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANSFERENCIA <=", value, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaIn(List<BigDecimal> values) {
            addCriterion("TRANSFERENCIA in", values, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaNotIn(List<BigDecimal> values) {
            addCriterion("TRANSFERENCIA not in", values, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferencianBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANSFERENCIA between", value1, value2, "transferencia");
            return (Criteria) this;
        }

        public Criteria andTransferenciaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANSFERENCIA not between", value1, value2, "transferencia");
            return (Criteria) this;
        }
        public Criteria andEcommerceIsNull() {
            addCriterion("ECOMMERCE is null");
            return (Criteria) this;
        }

        public Criteria andEcommerceIsNotNull() {
            addCriterion("ECOMMERCE is not null");
            return (Criteria) this;
        }

        public Criteria andEcommerceEqualTo(BigDecimal value) {
            addCriterion("ECOMMERCE =", value, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceNotEqualTo(BigDecimal value) {
            addCriterion("ECOMMERCE <>", value, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceGreaterThan(BigDecimal value) {
            addCriterion("ECOMMERCE >", value, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ECOMMERCE >=", value, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceLessThan(BigDecimal value) {
            addCriterion("ECOMMERCE <", value, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ECOMMERCE <=", value, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceIn(List<BigDecimal> values) {
            addCriterion("ECOMMERCE in", values, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceNotIn(List<BigDecimal> values) {
            addCriterion("ECOMMERCE not in", values, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ECOMMERCE between", value1, value2, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andEcommerceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ECOMMERCE not between", value1, value2, "ecommerce");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointIsNull() {
            addCriterion("VALE_FLEXPOINT is null");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointIsNotNull() {
            addCriterion("VALE_FLEXPOINT is not null");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointEqualTo(BigDecimal value) {
            addCriterion("VALE_FLEXPOINT =", value, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointNotEqualTo(BigDecimal value) {
            addCriterion("VALE_FLEXPOINT <>", value, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointGreaterThan(BigDecimal value) {
            addCriterion("VALE_FLEXPOINT >", value, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VALE_FLEXPOINT >=", value, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointLessThan(BigDecimal value) {
            addCriterion("VALE_FLEXPOINT <", value, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VALE_FLEXPOINT <=", value, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointIn(List<BigDecimal> values) {
            addCriterion("VALE_FLEXPOINT in", values, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointNotIn(List<BigDecimal> values) {
            addCriterion("VALE_FLEXPOINT not in", values, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALE_FLEXPOINT between", value1, value2, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeFlexpointNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALE_FLEXPOINT not between", value1, value2, "valeFlexpoint");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaIsNull() {
            addCriterion("VALE_COMERZZIA is null");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaIsNotNull() {
            addCriterion("VALE_COMERZZIA is not null");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaEqualTo(BigDecimal value) {
            addCriterion("VALE_COMERZZIA =", value, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaNotEqualTo(BigDecimal value) {
            addCriterion("VALE_COMERZZIA <>", value, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaGreaterThan(BigDecimal value) {
            addCriterion("VALE_COMERZZIA >", value, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VALE_COMERZZIA >=", value, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaLessThan(BigDecimal value) {
            addCriterion("VALE_COMERZZIA <", value, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VALE_COMERZZIA <=", value, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaIn(List<BigDecimal> values) {
            addCriterion("VALE_COMERZZIA in", values, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaNotIn(List<BigDecimal> values) {
            addCriterion("VALE_COMERZZIA not in", values, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALE_COMERZZIA between", value1, value2, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andValeComerzziaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALE_COMERZZIA not between", value1, value2, "valeComerzzia");
            return (Criteria) this;
        }

        public Criteria andGiftCardIsNull() {
            addCriterion("GIFT_CARD is null");
            return (Criteria) this;
        }

        public Criteria andGiftCardIsNotNull() {
            addCriterion("GIFT_CARD is not null");
            return (Criteria) this;
        }

        public Criteria andGiftCardEqualTo(BigDecimal value) {
            addCriterion("GIFT_CARD =", value, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardNotEqualTo(BigDecimal value) {
            addCriterion("GIFT_CARD <>", value, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardGreaterThan(BigDecimal value) {
            addCriterion("GIFT_CARD >", value, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GIFT_CARD >=", value, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardLessThan(BigDecimal value) {
            addCriterion("GIFT_CARD <", value, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GIFT_CARD <=", value, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardIn(List<BigDecimal> values) {
            addCriterion("GIFT_CARD in", values, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardNotIn(List<BigDecimal> values) {
            addCriterion("GIFT_CARD not in", values, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GIFT_CARD between", value1, value2, "giftCard");
            return (Criteria) this;
        }

        public Criteria andGiftCardNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GIFT_CARD not between", value1, value2, "giftCard");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoIsNull() {
            addCriterion("TARJETA_FIDELIZADO is null");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoIsNotNull() {
            addCriterion("TARJETA_FIDELIZADO is not null");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoEqualTo(BigDecimal value) {
            addCriterion("TARJETA_FIDELIZADO =", value, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoNotEqualTo(BigDecimal value) {
            addCriterion("TARJETA_FIDELIZADO <>", value, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoGreaterThan(BigDecimal value) {
            addCriterion("TARJETA_FIDELIZADO >", value, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TARJETA_FIDELIZADO >=", value, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoLessThan(BigDecimal value) {
            addCriterion("TARJETA_FIDELIZADO <", value, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TARJETA_FIDELIZADO <=", value, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoIn(List<BigDecimal> values) {
            addCriterion("TARJETA_FIDELIZADO in", values, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoNotIn(List<BigDecimal> values) {
            addCriterion("TARJETA_FIDELIZADO not in", values, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TARJETA_FIDELIZADO between", value1, value2, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andTarjetaFidelizadoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TARJETA_FIDELIZADO not between", value1, value2, "tarjetaFidelizado");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaIsNull() {
            addCriterion("CLIENTE_A_CUENTA is null");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaIsNotNull() {
            addCriterion("CLIENTE_A_CUENTA is not null");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaEqualTo(BigDecimal value) {
            addCriterion("CLIENTE_A_CUENTA =", value, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaNotEqualTo(BigDecimal value) {
            addCriterion("CLIENTE_A_CUENTA <>", value, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaGreaterThan(BigDecimal value) {
            addCriterion("CLIENTE_A_CUENTA >", value, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CLIENTE_A_CUENTA >=", value, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaLessThan(BigDecimal value) {
            addCriterion("CLIENTE_A_CUENTA <", value, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CLIENTE_A_CUENTA <=", value, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaIn(List<BigDecimal> values) {
            addCriterion("CLIENTE_A_CUENTA in", values, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaNotIn(List<BigDecimal> values) {
            addCriterion("CLIENTE_A_CUENTA not in", values, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLIENTE_A_CUENTA between", value1, value2, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andClienteACuentaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLIENTE_A_CUENTA not between", value1, value2, "clienteACuenta");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoIsNull() {
            addCriterion("ENVIADO_A_BANCO is null");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoIsNotNull() {
            addCriterion("ENVIADO_A_BANCO is not null");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoEqualTo(BigDecimal value) {
            addCriterion("ENVIADO_A_BANCO =", value, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoNotEqualTo(BigDecimal value) {
            addCriterion("ENVIADO_A_BANCO <>", value, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoGreaterThan(BigDecimal value) {
            addCriterion("ENVIADO_A_BANCO >", value, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ENVIADO_A_BANCO >=", value, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoLessThan(BigDecimal value) {
            addCriterion("ENVIADO_A_BANCO <", value, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ENVIADO_A_BANCO <=", value, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoIn(List<BigDecimal> values) {
            addCriterion("ENVIADO_A_BANCO in", values, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoNotIn(List<BigDecimal> values) {
            addCriterion("ENVIADO_A_BANCO not in", values, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENVIADO_A_BANCO between", value1, value2, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andEnviadoABancoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENVIADO_A_BANCO not between", value1, value2, "enviadoABanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoIsNull() {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO is null");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoIsNotNull() {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO is not null");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoEqualTo(BigDecimal value) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO =", value, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoNotEqualTo(BigDecimal value) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO <>", value, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoGreaterThan(BigDecimal value) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO >", value, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO >=", value, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoLessThan(BigDecimal value) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO <", value, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO <=", value, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoIn(List<BigDecimal> values) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO in", values, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoNotIn(List<BigDecimal> values) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO not in", values, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO between", value1, value2, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andImporteIngresadoEnBancoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMPORTE_INGRESADO_EN_BANCO not between", value1, value2, "importeIngresadoEnBanco");
            return (Criteria) this;
        }

        public Criteria andAportacionesIsNull() {
            addCriterion("APORTACIONES is null");
            return (Criteria) this;
        }

        public Criteria andAportacionesIsNotNull() {
            addCriterion("APORTACIONES is not null");
            return (Criteria) this;
        }

        public Criteria andAportacionesEqualTo(BigDecimal value) {
            addCriterion("APORTACIONES =", value, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesNotEqualTo(BigDecimal value) {
            addCriterion("APORTACIONES <>", value, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesGreaterThan(BigDecimal value) {
            addCriterion("APORTACIONES >", value, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APORTACIONES >=", value, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesLessThan(BigDecimal value) {
            addCriterion("APORTACIONES <", value, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APORTACIONES <=", value, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesIn(List<BigDecimal> values) {
            addCriterion("APORTACIONES in", values, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesNotIn(List<BigDecimal> values) {
            addCriterion("APORTACIONES not in", values, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APORTACIONES between", value1, value2, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andAportacionesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APORTACIONES not between", value1, value2, "aportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesIsNull() {
            addCriterion("DESAPORTACIONES is null");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesIsNotNull() {
            addCriterion("DESAPORTACIONES is not null");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesEqualTo(BigDecimal value) {
            addCriterion("DESAPORTACIONES =", value, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesNotEqualTo(BigDecimal value) {
            addCriterion("DESAPORTACIONES <>", value, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesGreaterThan(BigDecimal value) {
            addCriterion("DESAPORTACIONES >", value, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DESAPORTACIONES >=", value, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesLessThan(BigDecimal value) {
            addCriterion("DESAPORTACIONES <", value, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DESAPORTACIONES <=", value, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesIn(List<BigDecimal> values) {
            addCriterion("DESAPORTACIONES in", values, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesNotIn(List<BigDecimal> values) {
            addCriterion("DESAPORTACIONES not in", values, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESAPORTACIONES between", value1, value2, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andDesaportacionesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESAPORTACIONES not between", value1, value2, "desaportaciones");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaIsNull() {
            addCriterion("CAMBIOS_ENTRADA is null");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaIsNotNull() {
            addCriterion("CAMBIOS_ENTRADA is not null");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_ENTRADA =", value, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaNotEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_ENTRADA <>", value, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaGreaterThan(BigDecimal value) {
            addCriterion("CAMBIOS_ENTRADA >", value, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_ENTRADA >=", value, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaLessThan(BigDecimal value) {
            addCriterion("CAMBIOS_ENTRADA <", value, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_ENTRADA <=", value, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaIn(List<BigDecimal> values) {
            addCriterion("CAMBIOS_ENTRADA in", values, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaNotIn(List<BigDecimal> values) {
            addCriterion("CAMBIOS_ENTRADA not in", values, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CAMBIOS_ENTRADA between", value1, value2, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosEntradaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CAMBIOS_ENTRADA not between", value1, value2, "cambiosEntrada");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaIsNull() {
            addCriterion("CAMBIOS_SALIDA is null");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaIsNotNull() {
            addCriterion("CAMBIOS_SALIDA is not null");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_SALIDA =", value, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaNotEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_SALIDA <>", value, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaGreaterThan(BigDecimal value) {
            addCriterion("CAMBIOS_SALIDA >", value, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_SALIDA >=", value, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaLessThan(BigDecimal value) {
            addCriterion("CAMBIOS_SALIDA <", value, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CAMBIOS_SALIDA <=", value, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaIn(List<BigDecimal> values) {
            addCriterion("CAMBIOS_SALIDA in", values, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaNotIn(List<BigDecimal> values) {
            addCriterion("CAMBIOS_SALIDA not in", values, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CAMBIOS_SALIDA between", value1, value2, "cambiosSalida");
            return (Criteria) this;
        }

        public Criteria andCambiosSalidaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CAMBIOS_SALIDA not between", value1, value2, "cambiosSalida");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 28 13:57:12 CEST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_informe_tto_ventas_tbl
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}