package com.comerzzia.bricodepot.backoffice.persistence.ventas.informetto;

import java.util.Date;

public class InformeTtoVentasKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_tto_ventas_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_tto_ventas_tbl.FECHA
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_tto_ventas_tbl.CODALM
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    private String codalm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_tto_ventas_tbl.CODCAJA
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    private String codcaja;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_tto_ventas_tbl.UID_ACTIVIDAD
     *
     * @return the value of x_informe_tto_ventas_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_tto_ventas_tbl.UID_ACTIVIDAD
     *
     * @param uidActividad the value for x_informe_tto_ventas_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_tto_ventas_tbl.FECHA
     *
     * @return the value of x_informe_tto_ventas_tbl.FECHA
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_tto_ventas_tbl.FECHA
     *
     * @param fecha the value for x_informe_tto_ventas_tbl.FECHA
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_tto_ventas_tbl.CODALM
     *
     * @return the value of x_informe_tto_ventas_tbl.CODALM
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public String getCodalm() {
        return codalm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_tto_ventas_tbl.CODALM
     *
     * @param codalm the value for x_informe_tto_ventas_tbl.CODALM
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void setCodalm(String codalm) {
        this.codalm = codalm == null ? null : codalm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_tto_ventas_tbl.CODCAJA
     *
     * @return the value of x_informe_tto_ventas_tbl.CODCAJA
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public String getCodcaja() {
        return codcaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_tto_ventas_tbl.CODCAJA
     *
     * @param codcaja the value for x_informe_tto_ventas_tbl.CODCAJA
     *
     * @mbg.generated Fri Jun 28 13:57:12 CEST 2024
     */
    public void setCodcaja(String codcaja) {
        this.codcaja = codcaja == null ? null : codcaja.trim();
    }
}