package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.informepromocion;

import java.math.BigDecimal;
import java.util.Date;

public class InformePromociones {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.ID_FIDELIZADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private Long idFidelizado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.ID_PROMOCION
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private Long idPromocion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.CODALM
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String codalm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.DESALM
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String desalm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.VALOR_COBRADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private BigDecimal valorCobrado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.VALOR_DESCUENTO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private BigDecimal valorDescuento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.UID_TICKET
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String uidTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.NOMBRE_FIDELIZADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String nombreFidelizado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.COD_CAMPANIA
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String codCampania;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.DESCRIPCION_PROMOCION
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private String descripcionPromocion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_informe_promociones_tbl.FECHA
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    private Date fecha;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.UID_ACTIVIDAD
     *
     * @return the value of x_informe_promociones_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.UID_ACTIVIDAD
     *
     * @param uidActividad the value for x_informe_promociones_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.ID_FIDELIZADO
     *
     * @return the value of x_informe_promociones_tbl.ID_FIDELIZADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public Long getIdFidelizado() {
        return idFidelizado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.ID_FIDELIZADO
     *
     * @param idFidelizado the value for x_informe_promociones_tbl.ID_FIDELIZADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setIdFidelizado(Long idFidelizado) {
        this.idFidelizado = idFidelizado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.ID_PROMOCION
     *
     * @return the value of x_informe_promociones_tbl.ID_PROMOCION
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public Long getIdPromocion() {
        return idPromocion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.ID_PROMOCION
     *
     * @param idPromocion the value for x_informe_promociones_tbl.ID_PROMOCION
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setIdPromocion(Long idPromocion) {
        this.idPromocion = idPromocion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.CODALM
     *
     * @return the value of x_informe_promociones_tbl.CODALM
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getCodalm() {
        return codalm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.CODALM
     *
     * @param codalm the value for x_informe_promociones_tbl.CODALM
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setCodalm(String codalm) {
        this.codalm = codalm == null ? null : codalm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.DESALM
     *
     * @return the value of x_informe_promociones_tbl.DESALM
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getDesalm() {
        return desalm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.DESALM
     *
     * @param desalm the value for x_informe_promociones_tbl.DESALM
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setDesalm(String desalm) {
        this.desalm = desalm == null ? null : desalm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.VALOR_COBRADO
     *
     * @return the value of x_informe_promociones_tbl.VALOR_COBRADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public BigDecimal getValorCobrado() {
        return valorCobrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.VALOR_COBRADO
     *
     * @param valorCobrado the value for x_informe_promociones_tbl.VALOR_COBRADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setValorCobrado(BigDecimal valorCobrado) {
        this.valorCobrado = valorCobrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.VALOR_DESCUENTO
     *
     * @return the value of x_informe_promociones_tbl.VALOR_DESCUENTO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public BigDecimal getValorDescuento() {
        return valorDescuento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.VALOR_DESCUENTO
     *
     * @param valorDescuento the value for x_informe_promociones_tbl.VALOR_DESCUENTO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setValorDescuento(BigDecimal valorDescuento) {
        this.valorDescuento = valorDescuento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.UID_TICKET
     *
     * @return the value of x_informe_promociones_tbl.UID_TICKET
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getUidTicket() {
        return uidTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.UID_TICKET
     *
     * @param uidTicket the value for x_informe_promociones_tbl.UID_TICKET
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setUidTicket(String uidTicket) {
        this.uidTicket = uidTicket == null ? null : uidTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.NOMBRE_FIDELIZADO
     *
     * @return the value of x_informe_promociones_tbl.NOMBRE_FIDELIZADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getNombreFidelizado() {
        return nombreFidelizado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.NOMBRE_FIDELIZADO
     *
     * @param nombreFidelizado the value for x_informe_promociones_tbl.NOMBRE_FIDELIZADO
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setNombreFidelizado(String nombreFidelizado) {
        this.nombreFidelizado = nombreFidelizado == null ? null : nombreFidelizado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.COD_CAMPANIA
     *
     * @return the value of x_informe_promociones_tbl.COD_CAMPANIA
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getCodCampania() {
        return codCampania;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.COD_CAMPANIA
     *
     * @param codCampania the value for x_informe_promociones_tbl.COD_CAMPANIA
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setCodCampania(String codCampania) {
        this.codCampania = codCampania == null ? null : codCampania.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.DESCRIPCION_PROMOCION
     *
     * @return the value of x_informe_promociones_tbl.DESCRIPCION_PROMOCION
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getDescripcionPromocion() {
        return descripcionPromocion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.DESCRIPCION_PROMOCION
     *
     * @param descripcionPromocion the value for x_informe_promociones_tbl.DESCRIPCION_PROMOCION
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setDescripcionPromocion(String descripcionPromocion) {
        this.descripcionPromocion = descripcionPromocion == null ? null : descripcionPromocion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_informe_promociones_tbl.FECHA
     *
     * @return the value of x_informe_promociones_tbl.FECHA
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_informe_promociones_tbl.FECHA
     *
     * @param fecha the value for x_informe_promociones_tbl.FECHA
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}