package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.informepromocion;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InformePromocionesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public InformePromocionesExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("UID_ACTIVIDAD is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("UID_ACTIVIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("UID_ACTIVIDAD >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("UID_ACTIVIDAD <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("UID_ACTIVIDAD like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("UID_ACTIVIDAD not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoIsNull() {
            addCriterion("ID_FIDELIZADO is null");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoIsNotNull() {
            addCriterion("ID_FIDELIZADO is not null");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoEqualTo(Long value) {
            addCriterion("ID_FIDELIZADO =", value, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoNotEqualTo(Long value) {
            addCriterion("ID_FIDELIZADO <>", value, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoGreaterThan(Long value) {
            addCriterion("ID_FIDELIZADO >", value, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoGreaterThanOrEqualTo(Long value) {
            addCriterion("ID_FIDELIZADO >=", value, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoLessThan(Long value) {
            addCriterion("ID_FIDELIZADO <", value, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoLessThanOrEqualTo(Long value) {
            addCriterion("ID_FIDELIZADO <=", value, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoIn(List<Long> values) {
            addCriterion("ID_FIDELIZADO in", values, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoNotIn(List<Long> values) {
            addCriterion("ID_FIDELIZADO not in", values, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoBetween(Long value1, Long value2) {
            addCriterion("ID_FIDELIZADO between", value1, value2, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdFidelizadoNotBetween(Long value1, Long value2) {
            addCriterion("ID_FIDELIZADO not between", value1, value2, "idFidelizado");
            return (Criteria) this;
        }

        public Criteria andIdPromocionIsNull() {
            addCriterion("ID_PROMOCION is null");
            return (Criteria) this;
        }

        public Criteria andIdPromocionIsNotNull() {
            addCriterion("ID_PROMOCION is not null");
            return (Criteria) this;
        }

        public Criteria andIdPromocionEqualTo(Long value) {
            addCriterion("ID_PROMOCION =", value, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionNotEqualTo(Long value) {
            addCriterion("ID_PROMOCION <>", value, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionGreaterThan(Long value) {
            addCriterion("ID_PROMOCION >", value, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionGreaterThanOrEqualTo(Long value) {
            addCriterion("ID_PROMOCION >=", value, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionLessThan(Long value) {
            addCriterion("ID_PROMOCION <", value, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionLessThanOrEqualTo(Long value) {
            addCriterion("ID_PROMOCION <=", value, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionIn(List<Long> values) {
            addCriterion("ID_PROMOCION in", values, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionNotIn(List<Long> values) {
            addCriterion("ID_PROMOCION not in", values, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionBetween(Long value1, Long value2) {
            addCriterion("ID_PROMOCION between", value1, value2, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andIdPromocionNotBetween(Long value1, Long value2) {
            addCriterion("ID_PROMOCION not between", value1, value2, "idPromocion");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNull() {
            addCriterion("CODALM is null");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNotNull() {
            addCriterion("CODALM is not null");
            return (Criteria) this;
        }

        public Criteria andCodalmEqualTo(String value) {
            addCriterion("CODALM =", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotEqualTo(String value) {
            addCriterion("CODALM <>", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThan(String value) {
            addCriterion("CODALM >", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThanOrEqualTo(String value) {
            addCriterion("CODALM >=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThan(String value) {
            addCriterion("CODALM <", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThanOrEqualTo(String value) {
            addCriterion("CODALM <=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLike(String value) {
            addCriterion("CODALM like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotLike(String value) {
            addCriterion("CODALM not like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmIn(List<String> values) {
            addCriterion("CODALM in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotIn(List<String> values) {
            addCriterion("CODALM not in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmBetween(String value1, String value2) {
            addCriterion("CODALM between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotBetween(String value1, String value2) {
            addCriterion("CODALM not between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andDesalmIsNull() {
            addCriterion("DESALM is null");
            return (Criteria) this;
        }

        public Criteria andDesalmIsNotNull() {
            addCriterion("DESALM is not null");
            return (Criteria) this;
        }

        public Criteria andDesalmEqualTo(String value) {
            addCriterion("DESALM =", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmNotEqualTo(String value) {
            addCriterion("DESALM <>", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmGreaterThan(String value) {
            addCriterion("DESALM >", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmGreaterThanOrEqualTo(String value) {
            addCriterion("DESALM >=", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmLessThan(String value) {
            addCriterion("DESALM <", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmLessThanOrEqualTo(String value) {
            addCriterion("DESALM <=", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmLike(String value) {
            addCriterion("DESALM like", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmNotLike(String value) {
            addCriterion("DESALM not like", value, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmIn(List<String> values) {
            addCriterion("DESALM in", values, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmNotIn(List<String> values) {
            addCriterion("DESALM not in", values, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmBetween(String value1, String value2) {
            addCriterion("DESALM between", value1, value2, "desalm");
            return (Criteria) this;
        }

        public Criteria andDesalmNotBetween(String value1, String value2) {
            addCriterion("DESALM not between", value1, value2, "desalm");
            return (Criteria) this;
        }

        public Criteria andValorCobradoIsNull() {
            addCriterion("VALOR_COBRADO is null");
            return (Criteria) this;
        }

        public Criteria andValorCobradoIsNotNull() {
            addCriterion("VALOR_COBRADO is not null");
            return (Criteria) this;
        }

        public Criteria andValorCobradoEqualTo(BigDecimal value) {
            addCriterion("VALOR_COBRADO =", value, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoNotEqualTo(BigDecimal value) {
            addCriterion("VALOR_COBRADO <>", value, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoGreaterThan(BigDecimal value) {
            addCriterion("VALOR_COBRADO >", value, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VALOR_COBRADO >=", value, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoLessThan(BigDecimal value) {
            addCriterion("VALOR_COBRADO <", value, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VALOR_COBRADO <=", value, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoIn(List<BigDecimal> values) {
            addCriterion("VALOR_COBRADO in", values, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoNotIn(List<BigDecimal> values) {
            addCriterion("VALOR_COBRADO not in", values, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALOR_COBRADO between", value1, value2, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorCobradoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALOR_COBRADO not between", value1, value2, "valorCobrado");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoIsNull() {
            addCriterion("VALOR_DESCUENTO is null");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoIsNotNull() {
            addCriterion("VALOR_DESCUENTO is not null");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoEqualTo(BigDecimal value) {
            addCriterion("VALOR_DESCUENTO =", value, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoNotEqualTo(BigDecimal value) {
            addCriterion("VALOR_DESCUENTO <>", value, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoGreaterThan(BigDecimal value) {
            addCriterion("VALOR_DESCUENTO >", value, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VALOR_DESCUENTO >=", value, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoLessThan(BigDecimal value) {
            addCriterion("VALOR_DESCUENTO <", value, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VALOR_DESCUENTO <=", value, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoIn(List<BigDecimal> values) {
            addCriterion("VALOR_DESCUENTO in", values, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoNotIn(List<BigDecimal> values) {
            addCriterion("VALOR_DESCUENTO not in", values, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALOR_DESCUENTO between", value1, value2, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andValorDescuentoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VALOR_DESCUENTO not between", value1, value2, "valorDescuento");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNull() {
            addCriterion("UID_TICKET is null");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNotNull() {
            addCriterion("UID_TICKET is not null");
            return (Criteria) this;
        }

        public Criteria andUidTicketEqualTo(String value) {
            addCriterion("UID_TICKET =", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotEqualTo(String value) {
            addCriterion("UID_TICKET <>", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThan(String value) {
            addCriterion("UID_TICKET >", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThanOrEqualTo(String value) {
            addCriterion("UID_TICKET >=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThan(String value) {
            addCriterion("UID_TICKET <", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThanOrEqualTo(String value) {
            addCriterion("UID_TICKET <=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLike(String value) {
            addCriterion("UID_TICKET like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotLike(String value) {
            addCriterion("UID_TICKET not like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketIn(List<String> values) {
            addCriterion("UID_TICKET in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotIn(List<String> values) {
            addCriterion("UID_TICKET not in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketBetween(String value1, String value2) {
            addCriterion("UID_TICKET between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotBetween(String value1, String value2) {
            addCriterion("UID_TICKET not between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoIsNull() {
            addCriterion("NOMBRE_FIDELIZADO is null");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoIsNotNull() {
            addCriterion("NOMBRE_FIDELIZADO is not null");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoEqualTo(String value) {
            addCriterion("NOMBRE_FIDELIZADO =", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoNotEqualTo(String value) {
            addCriterion("NOMBRE_FIDELIZADO <>", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoGreaterThan(String value) {
            addCriterion("NOMBRE_FIDELIZADO >", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoGreaterThanOrEqualTo(String value) {
            addCriterion("NOMBRE_FIDELIZADO >=", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoLessThan(String value) {
            addCriterion("NOMBRE_FIDELIZADO <", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoLessThanOrEqualTo(String value) {
            addCriterion("NOMBRE_FIDELIZADO <=", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoLike(String value) {
            addCriterion("NOMBRE_FIDELIZADO like", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoNotLike(String value) {
            addCriterion("NOMBRE_FIDELIZADO not like", value, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoIn(List<String> values) {
            addCriterion("NOMBRE_FIDELIZADO in", values, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoNotIn(List<String> values) {
            addCriterion("NOMBRE_FIDELIZADO not in", values, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoBetween(String value1, String value2) {
            addCriterion("NOMBRE_FIDELIZADO between", value1, value2, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andNombreFidelizadoNotBetween(String value1, String value2) {
            addCriterion("NOMBRE_FIDELIZADO not between", value1, value2, "nombreFidelizado");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaIsNull() {
            addCriterion("COD_CAMPANIA is null");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaIsNotNull() {
            addCriterion("COD_CAMPANIA is not null");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaEqualTo(String value) {
            addCriterion("COD_CAMPANIA =", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaNotEqualTo(String value) {
            addCriterion("COD_CAMPANIA <>", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaGreaterThan(String value) {
            addCriterion("COD_CAMPANIA >", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaGreaterThanOrEqualTo(String value) {
            addCriterion("COD_CAMPANIA >=", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaLessThan(String value) {
            addCriterion("COD_CAMPANIA <", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaLessThanOrEqualTo(String value) {
            addCriterion("COD_CAMPANIA <=", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaLike(String value) {
            addCriterion("COD_CAMPANIA like", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaNotLike(String value) {
            addCriterion("COD_CAMPANIA not like", value, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaIn(List<String> values) {
            addCriterion("COD_CAMPANIA in", values, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaNotIn(List<String> values) {
            addCriterion("COD_CAMPANIA not in", values, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaBetween(String value1, String value2) {
            addCriterion("COD_CAMPANIA between", value1, value2, "codCampania");
            return (Criteria) this;
        }

        public Criteria andCodCampaniaNotBetween(String value1, String value2) {
            addCriterion("COD_CAMPANIA not between", value1, value2, "codCampania");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionIsNull() {
            addCriterion("DESCRIPCION_PROMOCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionIsNotNull() {
            addCriterion("DESCRIPCION_PROMOCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionEqualTo(String value) {
            addCriterion("DESCRIPCION_PROMOCION =", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionNotEqualTo(String value) {
            addCriterion("DESCRIPCION_PROMOCION <>", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionGreaterThan(String value) {
            addCriterion("DESCRIPCION_PROMOCION >", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_PROMOCION >=", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionLessThan(String value) {
            addCriterion("DESCRIPCION_PROMOCION <", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_PROMOCION <=", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionLike(String value) {
            addCriterion("DESCRIPCION_PROMOCION like", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionNotLike(String value) {
            addCriterion("DESCRIPCION_PROMOCION not like", value, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionIn(List<String> values) {
            addCriterion("DESCRIPCION_PROMOCION in", values, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionNotIn(List<String> values) {
            addCriterion("DESCRIPCION_PROMOCION not in", values, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_PROMOCION between", value1, value2, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andDescripcionPromocionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_PROMOCION not between", value1, value2, "descripcionPromocion");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("FECHA is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterion("FECHA =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterion("FECHA <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterion("FECHA >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterion("FECHA <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterion("FECHA <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterion("FECHA in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterion("FECHA not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterion("FECHA between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterion("FECHA not between", value1, value2, "fecha");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 20 15:06:14 CET 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}