package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.informepromocion;

import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.informepromocion.InformePromociones;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.informepromocion.InformePromocionesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InformePromocionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    long countByExample(InformePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    int deleteByExample(InformePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    int insert(InformePromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    int insertSelective(InformePromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    List<InformePromociones> selectByExample(InformePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    int updateByExampleSelective(@Param("row") InformePromociones row, @Param("example") InformePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_informe_promociones_tbl
     *
     * @mbg.generated Wed Nov 20 15:06:14 CET 2024
     */
    int updateByExample(@Param("row") InformePromociones row, @Param("example") InformePromocionesExample example);
}