server:
    port: 8080 
    servlet:
        contextPath: /api/v2/loyalty

spring:  
    main:
        allow-bean-definition-overriding: true
    application:
        name: "comerzzia api v2 unide loyalty"
    messages:
        basename: i18n/messages,i18n/loyalty-messages,i18n/custom-messages
    jackson:
       serialization:
          FAIL_ON_EMPTY_BEANS: false
    quartz:
       job-store-type: JDBC
       scheduler-name: loyalty       
       properties:           
          org.quartz.threadPool.threadCount: 5
          org.quartz.jobStore.misfireThreshold: 60000
          org.quartz.jobStore.isClustered: true 
          org.quartz.scheduler.instanceId: AUTO   
        
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/manage"        
      exposure:
        include: "*"
                  
logging:
    level:
        ROOT: INFO        
        com.comerzzia.api: DEBUG
        com.comerzzia.custom.api: DEBUG
        org.mybatis: INFO   
        org.springframework : INFO     
