package com.comerzzia.bricodepot.backoffice.persistence.movimientos.albaranes.pagos;

import com.comerzzia.bricodepot.backoffice.persistence.movimientos.albaranes.pagos.CustomCuentaMovimientoExample;
import com.comerzzia.bricodepot.backoffice.persistence.movimientos.albaranes.pagos.CustomCuentaMovimientoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomCuentaMovimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    long countByExample(CustomCuentaMovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    int deleteByExample(CustomCuentaMovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    int deleteByPrimaryKey(CustomCuentaMovimientoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    int insert(CustomCuentaMovimientoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    int insertSelective(CustomCuentaMovimientoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    List<CustomCuentaMovimientoKey> selectByExample(CustomCuentaMovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    int updateByExampleSelective(@Param("record") CustomCuentaMovimientoKey record, @Param("example") CustomCuentaMovimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cuentas_movimientos_tbl
     *
     * @mbg.generated Fri Nov 04 13:56:41 CET 2022
     */
    int updateByExample(@Param("record") CustomCuentaMovimientoKey record, @Param("example") CustomCuentaMovimientoExample example);
}