package com.comerzzia.bricodepot.backoffice.persistence.promociones;

import com.comerzzia.bricodepot.backoffice.persistence.promociones.CabeceraPromociones;
import com.comerzzia.bricodepot.backoffice.persistence.promociones.CabeceraPromocionesExample;
import com.comerzzia.bricodepot.backoffice.persistence.promociones.CabeceraPromocionesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CabeceraPromocionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    long countByExample(CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int deleteByExample(CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int deleteByPrimaryKey(CabeceraPromocionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int insert(CabeceraPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int insertSelective(CabeceraPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    List<CabeceraPromociones> selectByExampleWithBLOBs(CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    List<CabeceraPromociones> selectByExample(CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    CabeceraPromociones selectByPrimaryKey(CabeceraPromocionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int updateByExampleSelective(@Param("row") CabeceraPromociones row, @Param("example") CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int updateByExampleWithBLOBs(@Param("row") CabeceraPromociones row, @Param("example") CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int updateByExample(@Param("row") CabeceraPromociones row, @Param("example") CabeceraPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int updateByPrimaryKeySelective(CabeceraPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int updateByPrimaryKeyWithBLOBs(CabeceraPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_cab_tbl
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    int updateByPrimaryKey(CabeceraPromociones row);
}