package com.comerzzia.bricodepot.backoffice.persistence.promociones;

public class CabeceraPromocionesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_promociones_cab_tbl.uid_actividad
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_promociones_cab_tbl.id_promocion
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    private Long idPromocion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_promociones_cab_tbl.uid_actividad
     *
     * @return the value of d_promociones_cab_tbl.uid_actividad
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_promociones_cab_tbl.uid_actividad
     *
     * @param uidActividad the value for d_promociones_cab_tbl.uid_actividad
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_promociones_cab_tbl.id_promocion
     *
     * @return the value of d_promociones_cab_tbl.id_promocion
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    public Long getIdPromocion() {
        return idPromocion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_promociones_cab_tbl.id_promocion
     *
     * @param idPromocion the value for d_promociones_cab_tbl.id_promocion
     *
     * @mbg.generated Wed Jan 03 10:07:35 CET 2024
     */
    public void setIdPromocion(Long idPromocion) {
        this.idPromocion = idPromocion;
    }
}