package com.comerzzia.bricodepot.backoffice.persistence.albaranes;

public class AlbaranCabeceraKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_clie_albaranes_cab_tbl.uid_actividad
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_clie_albaranes_cab_tbl.id_clie_albaran
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    private Long idClieAlbaran;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_clie_albaranes_cab_tbl.uid_actividad
     *
     * @return the value of d_clie_albaranes_cab_tbl.uid_actividad
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_clie_albaranes_cab_tbl.uid_actividad
     *
     * @param uidActividad the value for d_clie_albaranes_cab_tbl.uid_actividad
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_clie_albaranes_cab_tbl.id_clie_albaran
     *
     * @return the value of d_clie_albaranes_cab_tbl.id_clie_albaran
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    public Long getIdClieAlbaran() {
        return idClieAlbaran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_clie_albaranes_cab_tbl.id_clie_albaran
     *
     * @param idClieAlbaran the value for d_clie_albaranes_cab_tbl.id_clie_albaran
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    public void setIdClieAlbaran(Long idClieAlbaran) {
        this.idClieAlbaran = idClieAlbaran;
    }
}