package com.comerzzia.bricodepot.backoffice.persistence.albaranes;

import com.comerzzia.bricodepot.backoffice.persistence.albaranes.AlbaranCabecera;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.AlbaranCabeceraExample;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.AlbaranCabeceraKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbaranCabeceraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    long countByExample(AlbaranCabeceraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int deleteByExample(AlbaranCabeceraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int deleteByPrimaryKey(AlbaranCabeceraKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int insert(AlbaranCabecera row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int insertSelective(AlbaranCabecera row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    List<AlbaranCabecera> selectByExample(AlbaranCabeceraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    AlbaranCabecera selectByPrimaryKey(AlbaranCabeceraKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int updateByExampleSelective(@Param("row") AlbaranCabecera row, @Param("example") AlbaranCabeceraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int updateByExample(@Param("row") AlbaranCabecera row, @Param("example") AlbaranCabeceraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int updateByPrimaryKeySelective(AlbaranCabecera row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_clie_albaranes_cab_tbl
     *
     * @mbg.generated Tue Jun 13 16:35:14 CEST 2023
     */
    int updateByPrimaryKey(AlbaranCabecera row);
}