package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.cambioprecio;

public class AlbaranVentasCambiosPreciosKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_ventas_cambios_precio_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_ventas_cambios_precio_tbl.ID_CAMBIO
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    private Long idCambio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_ventas_cambios_precio_tbl.ID_CLIE_ALBARAN
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    private Long idClieAlbaran;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_ventas_cambios_precio_tbl.LOCATOR_ID
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    private String locatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_ventas_cambios_precio_tbl.LINEA
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    private Integer linea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_ventas_cambios_precio_tbl.UID_ACTIVIDAD
     *
     * @return the value of x_clie_ventas_cambios_precio_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_ventas_cambios_precio_tbl.UID_ACTIVIDAD
     *
     * @param uidActividad the value for x_clie_ventas_cambios_precio_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_ventas_cambios_precio_tbl.ID_CAMBIO
     *
     * @return the value of x_clie_ventas_cambios_precio_tbl.ID_CAMBIO
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public Long getIdCambio() {
        return idCambio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_ventas_cambios_precio_tbl.ID_CAMBIO
     *
     * @param idCambio the value for x_clie_ventas_cambios_precio_tbl.ID_CAMBIO
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public void setIdCambio(Long idCambio) {
        this.idCambio = idCambio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_ventas_cambios_precio_tbl.ID_CLIE_ALBARAN
     *
     * @return the value of x_clie_ventas_cambios_precio_tbl.ID_CLIE_ALBARAN
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public Long getIdClieAlbaran() {
        return idClieAlbaran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_ventas_cambios_precio_tbl.ID_CLIE_ALBARAN
     *
     * @param idClieAlbaran the value for x_clie_ventas_cambios_precio_tbl.ID_CLIE_ALBARAN
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public void setIdClieAlbaran(Long idClieAlbaran) {
        this.idClieAlbaran = idClieAlbaran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_ventas_cambios_precio_tbl.LOCATOR_ID
     *
     * @return the value of x_clie_ventas_cambios_precio_tbl.LOCATOR_ID
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public String getLocatorId() {
        return locatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_ventas_cambios_precio_tbl.LOCATOR_ID
     *
     * @param locatorId the value for x_clie_ventas_cambios_precio_tbl.LOCATOR_ID
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public void setLocatorId(String locatorId) {
        this.locatorId = locatorId == null ? null : locatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_ventas_cambios_precio_tbl.LINEA
     *
     * @return the value of x_clie_ventas_cambios_precio_tbl.LINEA
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public Integer getLinea() {
        return linea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_ventas_cambios_precio_tbl.LINEA
     *
     * @param linea the value for x_clie_ventas_cambios_precio_tbl.LINEA
     *
     * @mbg.generated Wed Jan 31 11:16:53 CET 2024
     */
    public void setLinea(Integer linea) {
        this.linea = linea;
    }
}