package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.pagos.anticipos;

import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.pagos.anticipos.Anticipos;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.pagos.anticipos.AnticiposExample;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.pagos.anticipos.AnticiposKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnticiposMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    long countByExample(AnticiposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int deleteByExample(AnticiposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int deleteByPrimaryKey(AnticiposKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int insert(Anticipos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int insertSelective(Anticipos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    List<Anticipos> selectByExample(AnticiposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    Anticipos selectByPrimaryKey(AnticiposKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int updateByExampleSelective(@Param("record") Anticipos record, @Param("example") AnticiposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int updateByExample(@Param("record") Anticipos record, @Param("example") AnticiposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int updateByPrimaryKeySelective(Anticipos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    int updateByPrimaryKey(Anticipos record);
}