package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.pagos.anticipos;

import java.util.ArrayList;
import java.util.List;

public class AnticiposExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public AnticiposExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("UID_ACTIVIDAD is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("UID_ACTIVIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("UID_ACTIVIDAD >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("UID_ACTIVIDAD <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("UID_ACTIVIDAD like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("UID_ACTIVIDAD not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranIsNull() {
            addCriterion("ID_CLIE_ALBARAN is null");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranIsNotNull() {
            addCriterion("ID_CLIE_ALBARAN is not null");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranEqualTo(Long value) {
            addCriterion("ID_CLIE_ALBARAN =", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranNotEqualTo(Long value) {
            addCriterion("ID_CLIE_ALBARAN <>", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranGreaterThan(Long value) {
            addCriterion("ID_CLIE_ALBARAN >", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranGreaterThanOrEqualTo(Long value) {
            addCriterion("ID_CLIE_ALBARAN >=", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranLessThan(Long value) {
            addCriterion("ID_CLIE_ALBARAN <", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranLessThanOrEqualTo(Long value) {
            addCriterion("ID_CLIE_ALBARAN <=", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranIn(List<Long> values) {
            addCriterion("ID_CLIE_ALBARAN in", values, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranNotIn(List<Long> values) {
            addCriterion("ID_CLIE_ALBARAN not in", values, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranBetween(Long value1, Long value2) {
            addCriterion("ID_CLIE_ALBARAN between", value1, value2, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranNotBetween(Long value1, Long value2) {
            addCriterion("ID_CLIE_ALBARAN not between", value1, value2, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoIsNull() {
            addCriterion("NUM_ANTICIPO is null");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoIsNotNull() {
            addCriterion("NUM_ANTICIPO is not null");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoEqualTo(String value) {
            addCriterion("NUM_ANTICIPO =", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoNotEqualTo(String value) {
            addCriterion("NUM_ANTICIPO <>", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoGreaterThan(String value) {
            addCriterion("NUM_ANTICIPO >", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoGreaterThanOrEqualTo(String value) {
            addCriterion("NUM_ANTICIPO >=", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoLessThan(String value) {
            addCriterion("NUM_ANTICIPO <", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoLessThanOrEqualTo(String value) {
            addCriterion("NUM_ANTICIPO <=", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoLike(String value) {
            addCriterion("NUM_ANTICIPO like", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoNotLike(String value) {
            addCriterion("NUM_ANTICIPO not like", value, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoIn(List<String> values) {
            addCriterion("NUM_ANTICIPO in", values, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoNotIn(List<String> values) {
            addCriterion("NUM_ANTICIPO not in", values, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoBetween(String value1, String value2) {
            addCriterion("NUM_ANTICIPO between", value1, value2, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andNumAnticipoNotBetween(String value1, String value2) {
            addCriterion("NUM_ANTICIPO not between", value1, value2, "numAnticipo");
            return (Criteria) this;
        }

        public Criteria andImporteIsNull() {
            addCriterion("IMPORTE is null");
            return (Criteria) this;
        }

        public Criteria andImporteIsNotNull() {
            addCriterion("IMPORTE is not null");
            return (Criteria) this;
        }

        public Criteria andImporteEqualTo(String value) {
            addCriterion("IMPORTE =", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotEqualTo(String value) {
            addCriterion("IMPORTE <>", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteGreaterThan(String value) {
            addCriterion("IMPORTE >", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteGreaterThanOrEqualTo(String value) {
            addCriterion("IMPORTE >=", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteLessThan(String value) {
            addCriterion("IMPORTE <", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteLessThanOrEqualTo(String value) {
            addCriterion("IMPORTE <=", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteLike(String value) {
            addCriterion("IMPORTE like", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotLike(String value) {
            addCriterion("IMPORTE not like", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteIn(List<String> values) {
            addCriterion("IMPORTE in", values, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotIn(List<String> values) {
            addCriterion("IMPORTE not in", values, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteBetween(String value1, String value2) {
            addCriterion("IMPORTE between", value1, value2, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotBetween(String value1, String value2) {
            addCriterion("IMPORTE not between", value1, value2, "importe");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("ESTADO =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("ESTADO <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("ESTADO >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("ESTADO >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("ESTADO <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("ESTADO <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("ESTADO like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("ESTADO not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("ESTADO in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("ESTADO not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("ESTADO between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("ESTADO not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNull() {
            addCriterion("UID_TICKET is null");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNotNull() {
            addCriterion("UID_TICKET is not null");
            return (Criteria) this;
        }

        public Criteria andUidTicketEqualTo(String value) {
            addCriterion("UID_TICKET =", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotEqualTo(String value) {
            addCriterion("UID_TICKET <>", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThan(String value) {
            addCriterion("UID_TICKET >", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThanOrEqualTo(String value) {
            addCriterion("UID_TICKET >=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThan(String value) {
            addCriterion("UID_TICKET <", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThanOrEqualTo(String value) {
            addCriterion("UID_TICKET <=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLike(String value) {
            addCriterion("UID_TICKET like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotLike(String value) {
            addCriterion("UID_TICKET not like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketIn(List<String> values) {
            addCriterion("UID_TICKET in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotIn(List<String> values) {
            addCriterion("UID_TICKET not in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketBetween(String value1, String value2) {
            addCriterion("UID_TICKET between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotBetween(String value1, String value2) {
            addCriterion("UID_TICKET not between", value1, value2, "uidTicket");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 26 10:48:46 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_anticipos_tbl
     *
     * @mbg.generated Fri Nov 26 10:48:46 CET 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}