package com.comerzzia.bricodepot.backoffice.persistence.motivos.datos;

import java.math.BigDecimal;
import java.util.Date;

public class MotivosDatos extends MotivosDatosKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.cod_albaran
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String codAlbaran;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.cod_albaran_origen
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String codAlbaranOrigen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.fecha
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.codart
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String codart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.tipo_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String tipoMotivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.codigo_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String codigoMotivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.descripcion_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String descripcionMotivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.comentario_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private String comentarioMotivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.cantidad
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private BigDecimal cantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.precio_original
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private BigDecimal precioOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_motivos_datos_tbl.precio_final
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    private BigDecimal precioFinal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.cod_albaran
     *
     * @return the value of x_motivos_datos_tbl.cod_albaran
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getCodAlbaran() {
        return codAlbaran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.cod_albaran
     *
     * @param codAlbaran the value for x_motivos_datos_tbl.cod_albaran
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setCodAlbaran(String codAlbaran) {
        this.codAlbaran = codAlbaran == null ? null : codAlbaran.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.cod_albaran_origen
     *
     * @return the value of x_motivos_datos_tbl.cod_albaran_origen
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getCodAlbaranOrigen() {
        return codAlbaranOrigen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.cod_albaran_origen
     *
     * @param codAlbaranOrigen the value for x_motivos_datos_tbl.cod_albaran_origen
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setCodAlbaranOrigen(String codAlbaranOrigen) {
        this.codAlbaranOrigen = codAlbaranOrigen == null ? null : codAlbaranOrigen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.fecha
     *
     * @return the value of x_motivos_datos_tbl.fecha
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.fecha
     *
     * @param fecha the value for x_motivos_datos_tbl.fecha
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.codart
     *
     * @return the value of x_motivos_datos_tbl.codart
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getCodart() {
        return codart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.codart
     *
     * @param codart the value for x_motivos_datos_tbl.codart
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setCodart(String codart) {
        this.codart = codart == null ? null : codart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.tipo_motivo
     *
     * @return the value of x_motivos_datos_tbl.tipo_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getTipoMotivo() {
        return tipoMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.tipo_motivo
     *
     * @param tipoMotivo the value for x_motivos_datos_tbl.tipo_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setTipoMotivo(String tipoMotivo) {
        this.tipoMotivo = tipoMotivo == null ? null : tipoMotivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.codigo_motivo
     *
     * @return the value of x_motivos_datos_tbl.codigo_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getCodigoMotivo() {
        return codigoMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.codigo_motivo
     *
     * @param codigoMotivo the value for x_motivos_datos_tbl.codigo_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setCodigoMotivo(String codigoMotivo) {
        this.codigoMotivo = codigoMotivo == null ? null : codigoMotivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.descripcion_motivo
     *
     * @return the value of x_motivos_datos_tbl.descripcion_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getDescripcionMotivo() {
        return descripcionMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.descripcion_motivo
     *
     * @param descripcionMotivo the value for x_motivos_datos_tbl.descripcion_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setDescripcionMotivo(String descripcionMotivo) {
        this.descripcionMotivo = descripcionMotivo == null ? null : descripcionMotivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.comentario_motivo
     *
     * @return the value of x_motivos_datos_tbl.comentario_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getComentarioMotivo() {
        return comentarioMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.comentario_motivo
     *
     * @param comentarioMotivo the value for x_motivos_datos_tbl.comentario_motivo
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setComentarioMotivo(String comentarioMotivo) {
        this.comentarioMotivo = comentarioMotivo == null ? null : comentarioMotivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.cantidad
     *
     * @return the value of x_motivos_datos_tbl.cantidad
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public BigDecimal getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.cantidad
     *
     * @param cantidad the value for x_motivos_datos_tbl.cantidad
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.precio_original
     *
     * @return the value of x_motivos_datos_tbl.precio_original
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public BigDecimal getPrecioOriginal() {
        return precioOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.precio_original
     *
     * @param precioOriginal the value for x_motivos_datos_tbl.precio_original
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setPrecioOriginal(BigDecimal precioOriginal) {
        this.precioOriginal = precioOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_motivos_datos_tbl.precio_final
     *
     * @return the value of x_motivos_datos_tbl.precio_final
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public BigDecimal getPrecioFinal() {
        return precioFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_motivos_datos_tbl.precio_final
     *
     * @param precioFinal the value for x_motivos_datos_tbl.precio_final
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setPrecioFinal(BigDecimal precioFinal) {
        this.precioFinal = precioFinal;
    }
}