package com.comerzzia.bricodepot.backoffice.persistence.motivos.datos;

import com.comerzzia.bricodepot.backoffice.persistence.motivos.datos.MotivosDatos;
import com.comerzzia.bricodepot.backoffice.persistence.motivos.datos.MotivosDatosExample;
import com.comerzzia.bricodepot.backoffice.persistence.motivos.datos.MotivosDatosKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MotivosDatosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    long countByExample(MotivosDatosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int deleteByExample(MotivosDatosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int deleteByPrimaryKey(MotivosDatosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int insert(MotivosDatos row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int insertSelective(MotivosDatos row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    List<MotivosDatos> selectByExample(MotivosDatosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    MotivosDatos selectByPrimaryKey(MotivosDatosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int updateByExampleSelective(@Param("row") MotivosDatos row, @Param("example") MotivosDatosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int updateByExample(@Param("row") MotivosDatos row, @Param("example") MotivosDatosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int updateByPrimaryKeySelective(MotivosDatos row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    int updateByPrimaryKey(MotivosDatos row);
}