package com.comerzzia.bricodepot.backoffice.persistence.motivos.datos;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MotivosDatosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public MotivosDatosExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("uid_actividad is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("uid_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("uid_actividad =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("uid_actividad <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("uid_actividad >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("uid_actividad >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("uid_actividad <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("uid_actividad <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("uid_actividad like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("uid_actividad not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("uid_actividad in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("uid_actividad not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("uid_actividad between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("uid_actividad not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNull() {
            addCriterion("uid_ticket is null");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNotNull() {
            addCriterion("uid_ticket is not null");
            return (Criteria) this;
        }

        public Criteria andUidTicketEqualTo(String value) {
            addCriterion("uid_ticket =", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotEqualTo(String value) {
            addCriterion("uid_ticket <>", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThan(String value) {
            addCriterion("uid_ticket >", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThanOrEqualTo(String value) {
            addCriterion("uid_ticket >=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThan(String value) {
            addCriterion("uid_ticket <", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThanOrEqualTo(String value) {
            addCriterion("uid_ticket <=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLike(String value) {
            addCriterion("uid_ticket like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotLike(String value) {
            addCriterion("uid_ticket not like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketIn(List<String> values) {
            addCriterion("uid_ticket in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotIn(List<String> values) {
            addCriterion("uid_ticket not in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketBetween(String value1, String value2) {
            addCriterion("uid_ticket between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotBetween(String value1, String value2) {
            addCriterion("uid_ticket not between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andLineaIsNull() {
            addCriterion("linea is null");
            return (Criteria) this;
        }

        public Criteria andLineaIsNotNull() {
            addCriterion("linea is not null");
            return (Criteria) this;
        }

        public Criteria andLineaEqualTo(Integer value) {
            addCriterion("linea =", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaNotEqualTo(Integer value) {
            addCriterion("linea <>", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaGreaterThan(Integer value) {
            addCriterion("linea >", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaGreaterThanOrEqualTo(Integer value) {
            addCriterion("linea >=", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaLessThan(Integer value) {
            addCriterion("linea <", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaLessThanOrEqualTo(Integer value) {
            addCriterion("linea <=", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaIn(List<Integer> values) {
            addCriterion("linea in", values, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaNotIn(List<Integer> values) {
            addCriterion("linea not in", values, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaBetween(Integer value1, Integer value2) {
            addCriterion("linea between", value1, value2, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaNotBetween(Integer value1, Integer value2) {
            addCriterion("linea not between", value1, value2, "linea");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranIsNull() {
            addCriterion("cod_albaran is null");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranIsNotNull() {
            addCriterion("cod_albaran is not null");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranEqualTo(String value) {
            addCriterion("cod_albaran =", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranNotEqualTo(String value) {
            addCriterion("cod_albaran <>", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranGreaterThan(String value) {
            addCriterion("cod_albaran >", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranGreaterThanOrEqualTo(String value) {
            addCriterion("cod_albaran >=", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranLessThan(String value) {
            addCriterion("cod_albaran <", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranLessThanOrEqualTo(String value) {
            addCriterion("cod_albaran <=", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranLike(String value) {
            addCriterion("cod_albaran like", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranNotLike(String value) {
            addCriterion("cod_albaran not like", value, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranIn(List<String> values) {
            addCriterion("cod_albaran in", values, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranNotIn(List<String> values) {
            addCriterion("cod_albaran not in", values, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranBetween(String value1, String value2) {
            addCriterion("cod_albaran between", value1, value2, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranNotBetween(String value1, String value2) {
            addCriterion("cod_albaran not between", value1, value2, "codAlbaran");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenIsNull() {
            addCriterion("cod_albaran_origen is null");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenIsNotNull() {
            addCriterion("cod_albaran_origen is not null");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenEqualTo(String value) {
            addCriterion("cod_albaran_origen =", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenNotEqualTo(String value) {
            addCriterion("cod_albaran_origen <>", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenGreaterThan(String value) {
            addCriterion("cod_albaran_origen >", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenGreaterThanOrEqualTo(String value) {
            addCriterion("cod_albaran_origen >=", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenLessThan(String value) {
            addCriterion("cod_albaran_origen <", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenLessThanOrEqualTo(String value) {
            addCriterion("cod_albaran_origen <=", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenLike(String value) {
            addCriterion("cod_albaran_origen like", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenNotLike(String value) {
            addCriterion("cod_albaran_origen not like", value, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenIn(List<String> values) {
            addCriterion("cod_albaran_origen in", values, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenNotIn(List<String> values) {
            addCriterion("cod_albaran_origen not in", values, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenBetween(String value1, String value2) {
            addCriterion("cod_albaran_origen between", value1, value2, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andCodAlbaranOrigenNotBetween(String value1, String value2) {
            addCriterion("cod_albaran_origen not between", value1, value2, "codAlbaranOrigen");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("fecha is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("fecha is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterion("fecha =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterion("fecha <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterion("fecha >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterion("fecha <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterion("fecha <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterion("fecha in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterion("fecha not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterion("fecha between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterion("fecha not between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andCodartIsNull() {
            addCriterion("codart is null");
            return (Criteria) this;
        }

        public Criteria andCodartIsNotNull() {
            addCriterion("codart is not null");
            return (Criteria) this;
        }

        public Criteria andCodartEqualTo(String value) {
            addCriterion("codart =", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartNotEqualTo(String value) {
            addCriterion("codart <>", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartGreaterThan(String value) {
            addCriterion("codart >", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartGreaterThanOrEqualTo(String value) {
            addCriterion("codart >=", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartLessThan(String value) {
            addCriterion("codart <", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartLessThanOrEqualTo(String value) {
            addCriterion("codart <=", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartLike(String value) {
            addCriterion("codart like", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartNotLike(String value) {
            addCriterion("codart not like", value, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartIn(List<String> values) {
            addCriterion("codart in", values, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartNotIn(List<String> values) {
            addCriterion("codart not in", values, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartBetween(String value1, String value2) {
            addCriterion("codart between", value1, value2, "codart");
            return (Criteria) this;
        }

        public Criteria andCodartNotBetween(String value1, String value2) {
            addCriterion("codart not between", value1, value2, "codart");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoIsNull() {
            addCriterion("tipo_motivo is null");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoIsNotNull() {
            addCriterion("tipo_motivo is not null");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoEqualTo(String value) {
            addCriterion("tipo_motivo =", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoNotEqualTo(String value) {
            addCriterion("tipo_motivo <>", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoGreaterThan(String value) {
            addCriterion("tipo_motivo >", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoGreaterThanOrEqualTo(String value) {
            addCriterion("tipo_motivo >=", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoLessThan(String value) {
            addCriterion("tipo_motivo <", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoLessThanOrEqualTo(String value) {
            addCriterion("tipo_motivo <=", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoLike(String value) {
            addCriterion("tipo_motivo like", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoNotLike(String value) {
            addCriterion("tipo_motivo not like", value, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoIn(List<String> values) {
            addCriterion("tipo_motivo in", values, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoNotIn(List<String> values) {
            addCriterion("tipo_motivo not in", values, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoBetween(String value1, String value2) {
            addCriterion("tipo_motivo between", value1, value2, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andTipoMotivoNotBetween(String value1, String value2) {
            addCriterion("tipo_motivo not between", value1, value2, "tipoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoIsNull() {
            addCriterion("codigo_motivo is null");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoIsNotNull() {
            addCriterion("codigo_motivo is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoEqualTo(String value) {
            addCriterion("codigo_motivo =", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoNotEqualTo(String value) {
            addCriterion("codigo_motivo <>", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoGreaterThan(String value) {
            addCriterion("codigo_motivo >", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_motivo >=", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoLessThan(String value) {
            addCriterion("codigo_motivo <", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoLessThanOrEqualTo(String value) {
            addCriterion("codigo_motivo <=", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoLike(String value) {
            addCriterion("codigo_motivo like", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoNotLike(String value) {
            addCriterion("codigo_motivo not like", value, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoIn(List<String> values) {
            addCriterion("codigo_motivo in", values, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoNotIn(List<String> values) {
            addCriterion("codigo_motivo not in", values, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoBetween(String value1, String value2) {
            addCriterion("codigo_motivo between", value1, value2, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andCodigoMotivoNotBetween(String value1, String value2) {
            addCriterion("codigo_motivo not between", value1, value2, "codigoMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoIsNull() {
            addCriterion("descripcion_motivo is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoIsNotNull() {
            addCriterion("descripcion_motivo is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoEqualTo(String value) {
            addCriterion("descripcion_motivo =", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoNotEqualTo(String value) {
            addCriterion("descripcion_motivo <>", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoGreaterThan(String value) {
            addCriterion("descripcion_motivo >", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion_motivo >=", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoLessThan(String value) {
            addCriterion("descripcion_motivo <", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoLessThanOrEqualTo(String value) {
            addCriterion("descripcion_motivo <=", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoLike(String value) {
            addCriterion("descripcion_motivo like", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoNotLike(String value) {
            addCriterion("descripcion_motivo not like", value, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoIn(List<String> values) {
            addCriterion("descripcion_motivo in", values, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoNotIn(List<String> values) {
            addCriterion("descripcion_motivo not in", values, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoBetween(String value1, String value2) {
            addCriterion("descripcion_motivo between", value1, value2, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andDescripcionMotivoNotBetween(String value1, String value2) {
            addCriterion("descripcion_motivo not between", value1, value2, "descripcionMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoIsNull() {
            addCriterion("comentario_motivo is null");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoIsNotNull() {
            addCriterion("comentario_motivo is not null");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoEqualTo(String value) {
            addCriterion("comentario_motivo =", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoNotEqualTo(String value) {
            addCriterion("comentario_motivo <>", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoGreaterThan(String value) {
            addCriterion("comentario_motivo >", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoGreaterThanOrEqualTo(String value) {
            addCriterion("comentario_motivo >=", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoLessThan(String value) {
            addCriterion("comentario_motivo <", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoLessThanOrEqualTo(String value) {
            addCriterion("comentario_motivo <=", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoLike(String value) {
            addCriterion("comentario_motivo like", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoNotLike(String value) {
            addCriterion("comentario_motivo not like", value, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoIn(List<String> values) {
            addCriterion("comentario_motivo in", values, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoNotIn(List<String> values) {
            addCriterion("comentario_motivo not in", values, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoBetween(String value1, String value2) {
            addCriterion("comentario_motivo between", value1, value2, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andComentarioMotivoNotBetween(String value1, String value2) {
            addCriterion("comentario_motivo not between", value1, value2, "comentarioMotivo");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNull() {
            addCriterion("cantidad is null");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNotNull() {
            addCriterion("cantidad is not null");
            return (Criteria) this;
        }

        public Criteria andCantidadEqualTo(BigDecimal value) {
            addCriterion("cantidad =", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotEqualTo(BigDecimal value) {
            addCriterion("cantidad <>", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThan(BigDecimal value) {
            addCriterion("cantidad >", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cantidad >=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThan(BigDecimal value) {
            addCriterion("cantidad <", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cantidad <=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadIn(List<BigDecimal> values) {
            addCriterion("cantidad in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotIn(List<BigDecimal> values) {
            addCriterion("cantidad not in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cantidad between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cantidad not between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalIsNull() {
            addCriterion("precio_original is null");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalIsNotNull() {
            addCriterion("precio_original is not null");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalEqualTo(BigDecimal value) {
            addCriterion("precio_original =", value, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalNotEqualTo(BigDecimal value) {
            addCriterion("precio_original <>", value, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalGreaterThan(BigDecimal value) {
            addCriterion("precio_original >", value, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("precio_original >=", value, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalLessThan(BigDecimal value) {
            addCriterion("precio_original <", value, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("precio_original <=", value, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalIn(List<BigDecimal> values) {
            addCriterion("precio_original in", values, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalNotIn(List<BigDecimal> values) {
            addCriterion("precio_original not in", values, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("precio_original between", value1, value2, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioOriginalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("precio_original not between", value1, value2, "precioOriginal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalIsNull() {
            addCriterion("precio_final is null");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalIsNotNull() {
            addCriterion("precio_final is not null");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalEqualTo(BigDecimal value) {
            addCriterion("precio_final =", value, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalNotEqualTo(BigDecimal value) {
            addCriterion("precio_final <>", value, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalGreaterThan(BigDecimal value) {
            addCriterion("precio_final >", value, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("precio_final >=", value, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalLessThan(BigDecimal value) {
            addCriterion("precio_final <", value, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("precio_final <=", value, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalIn(List<BigDecimal> values) {
            addCriterion("precio_final in", values, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalNotIn(List<BigDecimal> values) {
            addCriterion("precio_final not in", values, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("precio_final between", value1, value2, "precioFinal");
            return (Criteria) this;
        }

        public Criteria andPrecioFinalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("precio_final not between", value1, value2, "precioFinal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 11 11:07:16 CET 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_motivos_datos_tbl
     *
     * @mbg.generated Thu Jan 11 11:07:16 CET 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}