package com.comerzzia.bricodepot.backoffice.persistence.fidelizacion.colectivos;

public class CustomColectivoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_colectivos_tbl.uid_instancia
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    private String uidInstancia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_colectivos_tbl.cod_colectivo
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    private String codColectivo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_colectivos_tbl.uid_instancia
     *
     * @return the value of x_colectivos_tbl.uid_instancia
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    public String getUidInstancia() {
        return uidInstancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_colectivos_tbl.uid_instancia
     *
     * @param uidInstancia the value for x_colectivos_tbl.uid_instancia
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    public void setUidInstancia(String uidInstancia) {
        this.uidInstancia = uidInstancia == null ? null : uidInstancia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_colectivos_tbl.cod_colectivo
     *
     * @return the value of x_colectivos_tbl.cod_colectivo
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    public String getCodColectivo() {
        return codColectivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_colectivos_tbl.cod_colectivo
     *
     * @param codColectivo the value for x_colectivos_tbl.cod_colectivo
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    public void setCodColectivo(String codColectivo) {
        this.codColectivo = codColectivo == null ? null : codColectivo.trim();
    }
}