package com.comerzzia.bricodepot.backoffice.persistence.fidelizacion.colectivos;

import com.comerzzia.bricodepot.backoffice.persistence.fidelizacion.colectivos.CustomColectivo;
import com.comerzzia.bricodepot.backoffice.persistence.fidelizacion.colectivos.CustomColectivoExample;
import com.comerzzia.bricodepot.backoffice.persistence.fidelizacion.colectivos.CustomColectivoKey;
import com.comerzzia.model.fidelizacion.colectivos.ColectivoBean;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CustomColectivoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    long countByExample(CustomColectivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int deleteByExample(CustomColectivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int deleteByPrimaryKey(CustomColectivoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int insert(CustomColectivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int insertSelective(CustomColectivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    List<CustomColectivo> selectByExample(CustomColectivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    CustomColectivo selectByPrimaryKey(CustomColectivoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int updateByExampleSelective(@Param("record") CustomColectivo record, @Param("example") CustomColectivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int updateByExample(@Param("record") CustomColectivo record, @Param("example") CustomColectivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int updateByPrimaryKeySelective(CustomColectivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_colectivos_tbl
     *
     * @mbg.generated Mon Feb 20 08:19:50 CET 2023
     */
    int updateByPrimaryKey(CustomColectivo record);
    
    /* ######################################## PERSONALIZADOS ######################################## */
    
    List<ColectivoBean> consultarTodosPublicosVisualizacionAltas(Map<String, String> map);
}