package com.comerzzia.bricodepot.backoffice.persistence.fidelizacion.fidelizados;

import java.util.List;

import com.comerzzia.model.fidelizacion.fidelizados.FidelizadoBean;
import com.comerzzia.model.fidelizacion.fidelizados.FidelizadoExample;

import org.apache.ibatis.annotations.Param;

public interface XFidelizadoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	long countByExample(XFidelizadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int deleteByExample(XFidelizadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int deleteByPrimaryKey(XFidelizadoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int insert(XFidelizado row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int insertSelective(XFidelizado row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	List<XFidelizado> selectByExample(XFidelizadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	XFidelizado selectByPrimaryKey(XFidelizadoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int updateByExampleSelective(@Param("row") XFidelizado row, @Param("example") XFidelizadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int updateByExample(@Param("row") XFidelizado row, @Param("example") XFidelizadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int updateByPrimaryKeySelective(XFidelizado row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table f_fidelizados_tbl
	 *
	 * @mbg.generated Tue Jun 20 15:19:47 CEST 2023
	 */
	int updateByPrimaryKey(XFidelizado row);

	List<FidelizadoBean> selectByExampleFidelizadoDatos(@Param("uidActividad") String uidActividad, @Param("example") FidelizadoExample example, @Param("codColectivos") List<String> codColectivos,
	        @Param("etiquetas") List<String> etiquetas, @Param("email") String email, @Param("phone") String phone);

}