package com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas.retirada;

public class DetMovRetiradaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_caja_det_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_caja_det_tbl.UID_DIARIO_CAJA
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    private String uidDiarioCaja;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_caja_det_tbl.LINEA
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    private Integer linea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_caja_det_tbl.UID_ACTIVIDAD
     *
     * @return the value of x_caja_det_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_caja_det_tbl.UID_ACTIVIDAD
     *
     * @param uidActividad the value for x_caja_det_tbl.UID_ACTIVIDAD
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_caja_det_tbl.UID_DIARIO_CAJA
     *
     * @return the value of x_caja_det_tbl.UID_DIARIO_CAJA
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    public String getUidDiarioCaja() {
        return uidDiarioCaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_caja_det_tbl.UID_DIARIO_CAJA
     *
     * @param uidDiarioCaja the value for x_caja_det_tbl.UID_DIARIO_CAJA
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    public void setUidDiarioCaja(String uidDiarioCaja) {
        this.uidDiarioCaja = uidDiarioCaja == null ? null : uidDiarioCaja.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_caja_det_tbl.LINEA
     *
     * @return the value of x_caja_det_tbl.LINEA
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    public Integer getLinea() {
        return linea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_caja_det_tbl.LINEA
     *
     * @param linea the value for x_caja_det_tbl.LINEA
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    public void setLinea(Integer linea) {
        this.linea = linea;
    }
}