package com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas.retirada;

import com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas.retirada.DetMovRetiradaExample;
import com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas.retirada.DetMovRetiradaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetMovRetiradaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    long countByExample(DetMovRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    int deleteByExample(DetMovRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    int deleteByPrimaryKey(DetMovRetiradaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    int insert(DetMovRetiradaKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    int insertSelective(DetMovRetiradaKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    List<DetMovRetiradaKey> selectByExample(DetMovRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    int updateByExampleSelective(@Param("row") DetMovRetiradaKey row, @Param("example") DetMovRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_caja_det_tbl
     *
     * @mbg.generated Tue Jan 16 11:58:54 CET 2024
     */
    int updateByExample(@Param("row") DetMovRetiradaKey row, @Param("example") DetMovRetiradaExample example);
}