package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.presupuestos;

import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.presupuestos.PresupuestoVenta;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.presupuestos.PresupuestoVentaExample;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.presupuestos.PresupuestoVentaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresupuestoVentaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    long countByExample(PresupuestoVentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int deleteByExample(PresupuestoVentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int deleteByPrimaryKey(PresupuestoVentaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int insert(PresupuestoVenta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int insertSelective(PresupuestoVenta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    List<PresupuestoVenta> selectByExample(PresupuestoVentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    PresupuestoVenta selectByPrimaryKey(PresupuestoVentaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int updateByExampleSelective(@Param("row") PresupuestoVenta row, @Param("example") PresupuestoVentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int updateByExample(@Param("row") PresupuestoVenta row, @Param("example") PresupuestoVentaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int updateByPrimaryKeySelective(PresupuestoVenta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_presupuesto_tbl
     *
     * @mbg.generated Mon May 20 09:15:40 CEST 2024
     */
    int updateByPrimaryKey(PresupuestoVenta row);
}