package com.comerzzia.bricodepot.backoffice.persistence.motivos;

import com.comerzzia.bricodepot.backoffice.persistence.motivos.Motivos;
import com.comerzzia.bricodepot.backoffice.persistence.motivos.MotivosExample;
import com.comerzzia.bricodepot.backoffice.persistence.motivos.MotivosKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MotivosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    long countByExample(MotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int deleteByExample(MotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int deleteByPrimaryKey(MotivosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int insert(Motivos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int insertSelective(Motivos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    List<Motivos> selectByExample(MotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    Motivos selectByPrimaryKey(MotivosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int updateByExampleSelective(@Param("record") Motivos record, @Param("example") MotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int updateByExample(@Param("record") Motivos record, @Param("example") MotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int updateByPrimaryKeySelective(Motivos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 12:41:16 CEST 2021
     */
    int updateByPrimaryKey(Motivos record);
}