package com.comerzzia.bricodepot.backoffice.persistence.promociones.detalle;

import com.comerzzia.bricodepot.backoffice.persistence.promociones.detalle.DetallePromociones;
import com.comerzzia.bricodepot.backoffice.persistence.promociones.detalle.DetallePromocionesExample;
import com.comerzzia.bricodepot.backoffice.persistence.promociones.detalle.DetallePromocionesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetallePromocionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    long countByExample(DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int deleteByExample(DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int deleteByPrimaryKey(DetallePromocionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int insert(DetallePromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int insertSelective(DetallePromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    List<DetallePromociones> selectByExampleWithBLOBs(DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    List<DetallePromociones> selectByExample(DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    DetallePromociones selectByPrimaryKey(DetallePromocionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int updateByExampleSelective(@Param("row") DetallePromociones row, @Param("example") DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int updateByExampleWithBLOBs(@Param("row") DetallePromociones row, @Param("example") DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int updateByExample(@Param("row") DetallePromociones row, @Param("example") DetallePromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int updateByPrimaryKeySelective(DetallePromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int updateByPrimaryKeyWithBLOBs(DetallePromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_det_tbl
     *
     * @mbg.generated Wed Jan 03 08:06:24 CET 2024
     */
    int updateByPrimaryKey(DetallePromociones row);
}