package com.comerzzia.bricodepot.backoffice.persistence.motivos.tipos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "tipos_motivos")
@XmlType(propOrder = { "uidActividad", "codigo_tipo" })
public class TiposMotivosKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * x_tipos_motivos_tbl.uid_actividad
	 *
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	@XmlElement(name = "uidActividad")
	private String uidActividad;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * x_tipos_motivos_tbl.codigo_tipo
	 *
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	@XmlElement(name = "codigo_tipo")
	private String codigoTipo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * x_tipos_motivos_tbl.uid_actividad
	 *
	 * @return the value of x_tipos_motivos_tbl.uid_actividad
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public String getUidActividad() {
		return uidActividad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * x_tipos_motivos_tbl.uid_actividad
	 *
	 * @param uidActividad
	 *            the value for x_tipos_motivos_tbl.uid_actividad
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public void setUidActividad(String uidActividad) {
		this.uidActividad = uidActividad == null ? null : uidActividad.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * x_tipos_motivos_tbl.codigo_tipo
	 *
	 * @return the value of x_tipos_motivos_tbl.codigo_tipo
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public String getCodigoTipo() {
		return codigoTipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * x_tipos_motivos_tbl.codigo_tipo
	 *
	 * @param codigoTipo
	 *            the value for x_tipos_motivos_tbl.codigo_tipo
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public void setCodigoTipo(String codigoTipo) {
		this.codigoTipo = codigoTipo == null ? null : codigoTipo.trim();
	}
}