package com.comerzzia.bricodepot.backoffice.persistence.motivos.tipos;

import javax.xml.bind.annotation.XmlElement;

public class TiposMotivos extends TiposMotivosKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * x_tipos_motivos_tbl.tipo
	 *
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	@XmlElement(name = "tipo")
	private String tipo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * x_tipos_motivos_tbl.descripcion
	 *
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	@XmlElement(name = "descripcion")
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * x_tipos_motivos_tbl.tipo
	 *
	 * @return the value of x_tipos_motivos_tbl.tipo
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * x_tipos_motivos_tbl.tipo
	 *
	 * @param tipo
	 *            the value for x_tipos_motivos_tbl.tipo
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo == null ? null : tipo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * x_tipos_motivos_tbl.descripcion
	 *
	 * @return the value of x_tipos_motivos_tbl.descripcion
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * x_tipos_motivos_tbl.descripcion
	 *
	 * @param descripcion
	 *            the value for x_tipos_motivos_tbl.descripcion
	 * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion == null ? null : descripcion.trim();
	}
}