package com.comerzzia.bricodepot.backoffice.persistence.motivos.tipos;

import com.comerzzia.bricodepot.backoffice.persistence.motivos.tipos.TiposMotivos;
import com.comerzzia.bricodepot.backoffice.persistence.motivos.tipos.TiposMotivosExample;
import com.comerzzia.bricodepot.backoffice.persistence.motivos.tipos.TiposMotivosKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TiposMotivosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    long countByExample(TiposMotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int deleteByExample(TiposMotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int deleteByPrimaryKey(TiposMotivosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int insert(TiposMotivos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int insertSelective(TiposMotivos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    List<TiposMotivos> selectByExample(TiposMotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    TiposMotivos selectByPrimaryKey(TiposMotivosKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int updateByExampleSelective(@Param("record") TiposMotivos record, @Param("example") TiposMotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int updateByExample(@Param("record") TiposMotivos record, @Param("example") TiposMotivosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int updateByPrimaryKeySelective(TiposMotivos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tipos_motivos_tbl
     *
     * @mbg.generated Wed Oct 06 09:03:41 CEST 2021
     */
    int updateByPrimaryKey(TiposMotivos record);
}