package com.comerzzia.bricodepot.backoffice.persistence.movimientos.retirada;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MovimientosRetiradaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public MovimientosRetiradaExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("UID_ACTIVIDAD is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("UID_ACTIVIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("UID_ACTIVIDAD >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("UID_ACTIVIDAD <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("UID_ACTIVIDAD like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("UID_ACTIVIDAD not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaIsNull() {
            addCriterion("UID_DIARIO_CAJA is null");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaIsNotNull() {
            addCriterion("UID_DIARIO_CAJA is not null");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaEqualTo(String value) {
            addCriterion("UID_DIARIO_CAJA =", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotEqualTo(String value) {
            addCriterion("UID_DIARIO_CAJA <>", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaGreaterThan(String value) {
            addCriterion("UID_DIARIO_CAJA >", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaGreaterThanOrEqualTo(String value) {
            addCriterion("UID_DIARIO_CAJA >=", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaLessThan(String value) {
            addCriterion("UID_DIARIO_CAJA <", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaLessThanOrEqualTo(String value) {
            addCriterion("UID_DIARIO_CAJA <=", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaLike(String value) {
            addCriterion("UID_DIARIO_CAJA like", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotLike(String value) {
            addCriterion("UID_DIARIO_CAJA not like", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaIn(List<String> values) {
            addCriterion("UID_DIARIO_CAJA in", values, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotIn(List<String> values) {
            addCriterion("UID_DIARIO_CAJA not in", values, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaBetween(String value1, String value2) {
            addCriterion("UID_DIARIO_CAJA between", value1, value2, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotBetween(String value1, String value2) {
            addCriterion("UID_DIARIO_CAJA not between", value1, value2, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andLinea91IsNull() {
            addCriterion("LINEA_91 is null");
            return (Criteria) this;
        }

        public Criteria andLinea91IsNotNull() {
            addCriterion("LINEA_91 is not null");
            return (Criteria) this;
        }

        public Criteria andLinea91EqualTo(Integer value) {
            addCriterion("LINEA_91 =", value, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91NotEqualTo(Integer value) {
            addCriterion("LINEA_91 <>", value, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91GreaterThan(Integer value) {
            addCriterion("LINEA_91 >", value, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91GreaterThanOrEqualTo(Integer value) {
            addCriterion("LINEA_91 >=", value, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91LessThan(Integer value) {
            addCriterion("LINEA_91 <", value, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91LessThanOrEqualTo(Integer value) {
            addCriterion("LINEA_91 <=", value, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91In(List<Integer> values) {
            addCriterion("LINEA_91 in", values, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91NotIn(List<Integer> values) {
            addCriterion("LINEA_91 not in", values, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91Between(Integer value1, Integer value2) {
            addCriterion("LINEA_91 between", value1, value2, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea91NotBetween(Integer value1, Integer value2) {
            addCriterion("LINEA_91 not between", value1, value2, "linea91");
            return (Criteria) this;
        }

        public Criteria andLinea90IsNull() {
            addCriterion("LINEA_90 is null");
            return (Criteria) this;
        }

        public Criteria andLinea90IsNotNull() {
            addCriterion("LINEA_90 is not null");
            return (Criteria) this;
        }

        public Criteria andLinea90EqualTo(Integer value) {
            addCriterion("LINEA_90 =", value, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90NotEqualTo(Integer value) {
            addCriterion("LINEA_90 <>", value, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90GreaterThan(Integer value) {
            addCriterion("LINEA_90 >", value, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90GreaterThanOrEqualTo(Integer value) {
            addCriterion("LINEA_90 >=", value, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90LessThan(Integer value) {
            addCriterion("LINEA_90 <", value, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90LessThanOrEqualTo(Integer value) {
            addCriterion("LINEA_90 <=", value, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90In(List<Integer> values) {
            addCriterion("LINEA_90 in", values, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90NotIn(List<Integer> values) {
            addCriterion("LINEA_90 not in", values, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90Between(Integer value1, Integer value2) {
            addCriterion("LINEA_90 between", value1, value2, "linea90");
            return (Criteria) this;
        }

        public Criteria andLinea90NotBetween(Integer value1, Integer value2) {
            addCriterion("LINEA_90 not between", value1, value2, "linea90");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaIsNull() {
            addCriterion("FECHA_BOLSA is null");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaIsNotNull() {
            addCriterion("FECHA_BOLSA is not null");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaEqualTo(Date value) {
            addCriterion("FECHA_BOLSA =", value, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaNotEqualTo(Date value) {
            addCriterion("FECHA_BOLSA <>", value, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaGreaterThan(Date value) {
            addCriterion("FECHA_BOLSA >", value, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA_BOLSA >=", value, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaLessThan(Date value) {
            addCriterion("FECHA_BOLSA <", value, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaLessThanOrEqualTo(Date value) {
            addCriterion("FECHA_BOLSA <=", value, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaIn(List<Date> values) {
            addCriterion("FECHA_BOLSA in", values, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaNotIn(List<Date> values) {
            addCriterion("FECHA_BOLSA not in", values, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaBetween(Date value1, Date value2) {
            addCriterion("FECHA_BOLSA between", value1, value2, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andFechaBolsaNotBetween(Date value1, Date value2) {
            addCriterion("FECHA_BOLSA not between", value1, value2, "fechaBolsa");
            return (Criteria) this;
        }

        public Criteria andImporteIsNull() {
            addCriterion("IMPORTE is null");
            return (Criteria) this;
        }

        public Criteria andImporteIsNotNull() {
            addCriterion("IMPORTE is not null");
            return (Criteria) this;
        }

        public Criteria andImporteEqualTo(BigDecimal value) {
            addCriterion("IMPORTE =", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotEqualTo(BigDecimal value) {
            addCriterion("IMPORTE <>", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteGreaterThan(BigDecimal value) {
            addCriterion("IMPORTE >", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IMPORTE >=", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteLessThan(BigDecimal value) {
            addCriterion("IMPORTE <", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IMPORTE <=", value, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteIn(List<BigDecimal> values) {
            addCriterion("IMPORTE in", values, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotIn(List<BigDecimal> values) {
            addCriterion("IMPORTE not in", values, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMPORTE between", value1, value2, "importe");
            return (Criteria) this;
        }

        public Criteria andImporteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMPORTE not between", value1, value2, "importe");
            return (Criteria) this;
        }

        public Criteria andDocumentoIsNull() {
            addCriterion("DOCUMENTO is null");
            return (Criteria) this;
        }

        public Criteria andDocumentoIsNotNull() {
            addCriterion("DOCUMENTO is not null");
            return (Criteria) this;
        }

        public Criteria andDocumentoEqualTo(String value) {
            addCriterion("DOCUMENTO =", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoNotEqualTo(String value) {
            addCriterion("DOCUMENTO <>", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoGreaterThan(String value) {
            addCriterion("DOCUMENTO >", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoGreaterThanOrEqualTo(String value) {
            addCriterion("DOCUMENTO >=", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoLessThan(String value) {
            addCriterion("DOCUMENTO <", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoLessThanOrEqualTo(String value) {
            addCriterion("DOCUMENTO <=", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoLike(String value) {
            addCriterion("DOCUMENTO like", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoNotLike(String value) {
            addCriterion("DOCUMENTO not like", value, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoIn(List<String> values) {
            addCriterion("DOCUMENTO in", values, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoNotIn(List<String> values) {
            addCriterion("DOCUMENTO not in", values, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoBetween(String value1, String value2) {
            addCriterion("DOCUMENTO between", value1, value2, "documento");
            return (Criteria) this;
        }

        public Criteria andDocumentoNotBetween(String value1, String value2) {
            addCriterion("DOCUMENTO not between", value1, value2, "documento");
            return (Criteria) this;
        }

        public Criteria andUsuarioIsNull() {
            addCriterion("USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioIsNotNull() {
            addCriterion("USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioEqualTo(String value) {
            addCriterion("USUARIO =", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotEqualTo(String value) {
            addCriterion("USUARIO <>", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioGreaterThan(String value) {
            addCriterion("USUARIO >", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("USUARIO >=", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLessThan(String value) {
            addCriterion("USUARIO <", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLessThanOrEqualTo(String value) {
            addCriterion("USUARIO <=", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLike(String value) {
            addCriterion("USUARIO like", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotLike(String value) {
            addCriterion("USUARIO not like", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioIn(List<String> values) {
            addCriterion("USUARIO in", values, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotIn(List<String> values) {
            addCriterion("USUARIO not in", values, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioBetween(String value1, String value2) {
            addCriterion("USUARIO between", value1, value2, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotBetween(String value1, String value2) {
            addCriterion("USUARIO not between", value1, value2, "usuario");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 21 12:10:31 CEST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}