package com.comerzzia.bricodepot.backoffice.persistence.movimientos.retirada;

import com.comerzzia.bricodepot.backoffice.persistence.movimientos.retirada.MovimientosRetirada;
import com.comerzzia.bricodepot.backoffice.persistence.movimientos.retirada.MovimientosRetiradaExample;
import com.comerzzia.bricodepot.backoffice.persistence.movimientos.retirada.MovimientosRetiradaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovimientosRetiradaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    long countByExample(MovimientosRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int deleteByExample(MovimientosRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int deleteByPrimaryKey(MovimientosRetiradaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int insert(MovimientosRetirada record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int insertSelective(MovimientosRetirada record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    List<MovimientosRetirada> selectByExample(MovimientosRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    MovimientosRetirada selectByPrimaryKey(MovimientosRetiradaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int updateByExampleSelective(@Param("record") MovimientosRetirada record, @Param("example") MovimientosRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int updateByExample(@Param("record") MovimientosRetirada record, @Param("example") MovimientosRetiradaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
    int updateByPrimaryKeySelective(MovimientosRetirada record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_movimientos_retiradas_banco_tbl
     *
     * @mbg.generated Fri Jun 21 12:10:31 CEST 2024
     */
	int updateByPrimaryKey(MovimientosRetirada record);

	Integer existeMovimientoRetirada(MovimientosRetirada movRetirada);
}