package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.pagos;

public class CustomAlbaranPag extends CustomAlbaranPagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_albaranes_pag_tbl.NUM_PEDIDO
     *
     * @mbg.generated Fri Nov 19 11:38:21 CET 2021
     */
    private String numPedido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_clie_albaranes_pag_tbl.NUM_FINANCIACION
     *
     * @mbg.generated Fri Nov 19 11:38:21 CET 2021
     */
    private String numFinanciacion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_albaranes_pag_tbl.NUM_PEDIDO
     *
     * @return the value of x_clie_albaranes_pag_tbl.NUM_PEDIDO
     *
     * @mbg.generated Fri Nov 19 11:38:21 CET 2021
     */
    public String getNumPedido() {
        return numPedido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_albaranes_pag_tbl.NUM_PEDIDO
     *
     * @param numPedido the value for x_clie_albaranes_pag_tbl.NUM_PEDIDO
     *
     * @mbg.generated Fri Nov 19 11:38:21 CET 2021
     */
    public void setNumPedido(String numPedido) {
        this.numPedido = numPedido == null ? null : numPedido.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_clie_albaranes_pag_tbl.NUM_FINANCIACION
     *
     * @return the value of x_clie_albaranes_pag_tbl.NUM_FINANCIACION
     *
     * @mbg.generated Fri Nov 19 11:38:21 CET 2021
     */
    public String getNumFinanciacion() {
        return numFinanciacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_clie_albaranes_pag_tbl.NUM_FINANCIACION
     *
     * @param numFinanciacion the value for x_clie_albaranes_pag_tbl.NUM_FINANCIACION
     *
     * @mbg.generated Fri Nov 19 11:38:21 CET 2021
     */
    public void setNumFinanciacion(String numFinanciacion) {
        this.numFinanciacion = numFinanciacion == null ? null : numFinanciacion.trim();
    }
}