package com.comerzzia.bricodepot.backoffice.persistence.devoluciones.maxDias;

import com.comerzzia.bricodepot.backoffice.persistence.devoluciones.maxDias.DiasDevolucion;
import com.comerzzia.bricodepot.backoffice.persistence.devoluciones.maxDias.DiasDevolucionExample;
import com.comerzzia.bricodepot.backoffice.persistence.devoluciones.maxDias.DiasDevolucionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiasDevolucionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    long countByExample(DiasDevolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int deleteByExample(DiasDevolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int deleteByPrimaryKey(DiasDevolucionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int insert(DiasDevolucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int insertSelective(DiasDevolucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    List<DiasDevolucion> selectByExample(DiasDevolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    DiasDevolucion selectByPrimaryKey(DiasDevolucionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int updateByExampleSelective(@Param("record") DiasDevolucion record, @Param("example") DiasDevolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int updateByExample(@Param("record") DiasDevolucion record, @Param("example") DiasDevolucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int updateByPrimaryKeySelective(DiasDevolucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    int updateByPrimaryKey(DiasDevolucion record);
}