package com.comerzzia.bricodepot.backoffice.persistence.devoluciones.maxDias;

import java.util.ArrayList;
import java.util.List;

public class DiasDevolucionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public DiasDevolucionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("uid_actividad is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("uid_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("uid_actividad =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("uid_actividad <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("uid_actividad >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("uid_actividad >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("uid_actividad <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("uid_actividad <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("uid_actividad like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("uid_actividad not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("uid_actividad in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("uid_actividad not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("uid_actividad between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("uid_actividad not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranIsNull() {
            addCriterion("id_albaran is null");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranIsNotNull() {
            addCriterion("id_albaran is not null");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranEqualTo(String value) {
            addCriterion("id_albaran =", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranNotEqualTo(String value) {
            addCriterion("id_albaran <>", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranGreaterThan(String value) {
            addCriterion("id_albaran >", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranGreaterThanOrEqualTo(String value) {
            addCriterion("id_albaran >=", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranLessThan(String value) {
            addCriterion("id_albaran <", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranLessThanOrEqualTo(String value) {
            addCriterion("id_albaran <=", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranLike(String value) {
            addCriterion("id_albaran like", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranNotLike(String value) {
            addCriterion("id_albaran not like", value, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranIn(List<String> values) {
            addCriterion("id_albaran in", values, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranNotIn(List<String> values) {
            addCriterion("id_albaran not in", values, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranBetween(String value1, String value2) {
            addCriterion("id_albaran between", value1, value2, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdAlbaranNotBetween(String value1, String value2) {
            addCriterion("id_albaran not between", value1, value2, "idAlbaran");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionIsNull() {
            addCriterion("fecha_devolucion is null");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionIsNotNull() {
            addCriterion("fecha_devolucion is not null");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionEqualTo(String value) {
            addCriterion("fecha_devolucion =", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionNotEqualTo(String value) {
            addCriterion("fecha_devolucion <>", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionGreaterThan(String value) {
            addCriterion("fecha_devolucion >", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionGreaterThanOrEqualTo(String value) {
            addCriterion("fecha_devolucion >=", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionLessThan(String value) {
            addCriterion("fecha_devolucion <", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionLessThanOrEqualTo(String value) {
            addCriterion("fecha_devolucion <=", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionLike(String value) {
            addCriterion("fecha_devolucion like", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionNotLike(String value) {
            addCriterion("fecha_devolucion not like", value, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionIn(List<String> values) {
            addCriterion("fecha_devolucion in", values, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionNotIn(List<String> values) {
            addCriterion("fecha_devolucion not in", values, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionBetween(String value1, String value2) {
            addCriterion("fecha_devolucion between", value1, value2, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaDevolucionNotBetween(String value1, String value2) {
            addCriterion("fecha_devolucion not between", value1, value2, "fechaDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionIsNull() {
            addCriterion("fecha_max_devolucion is null");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionIsNotNull() {
            addCriterion("fecha_max_devolucion is not null");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionEqualTo(String value) {
            addCriterion("fecha_max_devolucion =", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionNotEqualTo(String value) {
            addCriterion("fecha_max_devolucion <>", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionGreaterThan(String value) {
            addCriterion("fecha_max_devolucion >", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionGreaterThanOrEqualTo(String value) {
            addCriterion("fecha_max_devolucion >=", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionLessThan(String value) {
            addCriterion("fecha_max_devolucion <", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionLessThanOrEqualTo(String value) {
            addCriterion("fecha_max_devolucion <=", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionLike(String value) {
            addCriterion("fecha_max_devolucion like", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionNotLike(String value) {
            addCriterion("fecha_max_devolucion not like", value, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionIn(List<String> values) {
            addCriterion("fecha_max_devolucion in", values, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionNotIn(List<String> values) {
            addCriterion("fecha_max_devolucion not in", values, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionBetween(String value1, String value2) {
            addCriterion("fecha_max_devolucion between", value1, value2, "fechaMaxDevolucion");
            return (Criteria) this;
        }

        public Criteria andFechaMaxDevolucionNotBetween(String value1, String value2) {
            addCriterion("fecha_max_devolucion not between", value1, value2, "fechaMaxDevolucion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 20 13:38:04 CEST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_max_dias_devolucion_tbl
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}