package com.comerzzia.bricodepot.backoffice.persistence.devoluciones.maxDias;

public class DiasDevolucion extends DiasDevolucionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_max_dias_devolucion_tbl.fecha_devolucion
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    private String fechaDevolucion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_max_dias_devolucion_tbl.fecha_max_devolucion
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    private String fechaMaxDevolucion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_max_dias_devolucion_tbl.fecha_devolucion
     *
     * @return the value of x_max_dias_devolucion_tbl.fecha_devolucion
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public String getFechaDevolucion() {
        return fechaDevolucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_max_dias_devolucion_tbl.fecha_devolucion
     *
     * @param fechaDevolucion the value for x_max_dias_devolucion_tbl.fecha_devolucion
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public void setFechaDevolucion(String fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion == null ? null : fechaDevolucion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_max_dias_devolucion_tbl.fecha_max_devolucion
     *
     * @return the value of x_max_dias_devolucion_tbl.fecha_max_devolucion
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public String getFechaMaxDevolucion() {
        return fechaMaxDevolucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_max_dias_devolucion_tbl.fecha_max_devolucion
     *
     * @param fechaMaxDevolucion the value for x_max_dias_devolucion_tbl.fecha_max_devolucion
     *
     * @mbg.generated Wed Oct 20 13:38:04 CEST 2021
     */
    public void setFechaMaxDevolucion(String fechaMaxDevolucion) {
        this.fechaMaxDevolucion = fechaMaxDevolucion == null ? null : fechaMaxDevolucion.trim();
    }
}