package com.comerzzia.bricodepot.backoffice.persistence.devoluciones.validacion;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ValidacionDevolucionAlbaranExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public ValidacionDevolucionAlbaranExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> validadoCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
            validadoCriteria = new ArrayList<>();
        }

        public List<Criterion> getValidadoCriteria() {
            return validadoCriteria;
        }

        protected void addValidadoCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            validadoCriteria.add(new Criterion(condition, value, "com.comerzzia.core.util.mybatis.typehandlers.BooleanStringTypeHandler"));
            allCriteria = null;
        }

        protected void addValidadoCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            validadoCriteria.add(new Criterion(condition, value1, value2, "com.comerzzia.core.util.mybatis.typehandlers.BooleanStringTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || validadoCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(validadoCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("uid_actividad is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("uid_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("uid_actividad =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("uid_actividad <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("uid_actividad >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("uid_actividad >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("uid_actividad <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("uid_actividad <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("uid_actividad like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("uid_actividad not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("uid_actividad in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("uid_actividad not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("uid_actividad between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("uid_actividad not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranIsNull() {
            addCriterion("id_clie_albaran is null");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranIsNotNull() {
            addCriterion("id_clie_albaran is not null");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranEqualTo(Long value) {
            addCriterion("id_clie_albaran =", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranNotEqualTo(Long value) {
            addCriterion("id_clie_albaran <>", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranGreaterThan(Long value) {
            addCriterion("id_clie_albaran >", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranGreaterThanOrEqualTo(Long value) {
            addCriterion("id_clie_albaran >=", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranLessThan(Long value) {
            addCriterion("id_clie_albaran <", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranLessThanOrEqualTo(Long value) {
            addCriterion("id_clie_albaran <=", value, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranIn(List<Long> values) {
            addCriterion("id_clie_albaran in", values, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranNotIn(List<Long> values) {
            addCriterion("id_clie_albaran not in", values, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranBetween(Long value1, Long value2) {
            addCriterion("id_clie_albaran between", value1, value2, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andIdClieAlbaranNotBetween(Long value1, Long value2) {
            addCriterion("id_clie_albaran not between", value1, value2, "idClieAlbaran");
            return (Criteria) this;
        }

        public Criteria andLineaIsNull() {
            addCriterion("linea is null");
            return (Criteria) this;
        }

        public Criteria andLineaIsNotNull() {
            addCriterion("linea is not null");
            return (Criteria) this;
        }

        public Criteria andLineaEqualTo(Integer value) {
            addCriterion("linea =", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaNotEqualTo(Integer value) {
            addCriterion("linea <>", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaGreaterThan(Integer value) {
            addCriterion("linea >", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaGreaterThanOrEqualTo(Integer value) {
            addCriterion("linea >=", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaLessThan(Integer value) {
            addCriterion("linea <", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaLessThanOrEqualTo(Integer value) {
            addCriterion("linea <=", value, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaIn(List<Integer> values) {
            addCriterion("linea in", values, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaNotIn(List<Integer> values) {
            addCriterion("linea not in", values, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaBetween(Integer value1, Integer value2) {
            addCriterion("linea between", value1, value2, "linea");
            return (Criteria) this;
        }

        public Criteria andLineaNotBetween(Integer value1, Integer value2) {
            addCriterion("linea not between", value1, value2, "linea");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorIsNull() {
            addCriterion("id_usuario_supervisor is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorIsNotNull() {
            addCriterion("id_usuario_supervisor is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorEqualTo(Long value) {
            addCriterion("id_usuario_supervisor =", value, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorNotEqualTo(Long value) {
            addCriterion("id_usuario_supervisor <>", value, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorGreaterThan(Long value) {
            addCriterion("id_usuario_supervisor >", value, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorGreaterThanOrEqualTo(Long value) {
            addCriterion("id_usuario_supervisor >=", value, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorLessThan(Long value) {
            addCriterion("id_usuario_supervisor <", value, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorLessThanOrEqualTo(Long value) {
            addCriterion("id_usuario_supervisor <=", value, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorIn(List<Long> values) {
            addCriterion("id_usuario_supervisor in", values, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorNotIn(List<Long> values) {
            addCriterion("id_usuario_supervisor not in", values, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorBetween(Long value1, Long value2) {
            addCriterion("id_usuario_supervisor between", value1, value2, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioSupervisorNotBetween(Long value1, Long value2) {
            addCriterion("id_usuario_supervisor not between", value1, value2, "idUsuarioSupervisor");
            return (Criteria) this;
        }

        public Criteria andValidadoIsNull() {
            addCriterion("validado is null");
            return (Criteria) this;
        }

        public Criteria andValidadoIsNotNull() {
            addCriterion("validado is not null");
            return (Criteria) this;
        }

        public Criteria andValidadoEqualTo(Boolean value) {
            addValidadoCriterion("validado =", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoNotEqualTo(Boolean value) {
            addValidadoCriterion("validado <>", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoGreaterThan(Boolean value) {
            addValidadoCriterion("validado >", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoGreaterThanOrEqualTo(Boolean value) {
            addValidadoCriterion("validado >=", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoLessThan(Boolean value) {
            addValidadoCriterion("validado <", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoLessThanOrEqualTo(Boolean value) {
            addValidadoCriterion("validado <=", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoLike(Boolean value) {
            addValidadoCriterion("validado like", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoNotLike(Boolean value) {
            addValidadoCriterion("validado not like", value, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoIn(List<Boolean> values) {
            addValidadoCriterion("validado in", values, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoNotIn(List<Boolean> values) {
            addValidadoCriterion("validado not in", values, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoBetween(Boolean value1, Boolean value2) {
            addValidadoCriterion("validado between", value1, value2, "validado");
            return (Criteria) this;
        }

        public Criteria andValidadoNotBetween(Boolean value1, Boolean value2) {
            addValidadoCriterion("validado not between", value1, value2, "validado");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionIsNull() {
            addCriterion("fecha_validacion is null");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionIsNotNull() {
            addCriterion("fecha_validacion is not null");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionEqualTo(Date value) {
            addCriterion("fecha_validacion =", value, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionNotEqualTo(Date value) {
            addCriterion("fecha_validacion <>", value, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionGreaterThan(Date value) {
            addCriterion("fecha_validacion >", value, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_validacion >=", value, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionLessThan(Date value) {
            addCriterion("fecha_validacion <", value, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionLessThanOrEqualTo(Date value) {
            addCriterion("fecha_validacion <=", value, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionIn(List<Date> values) {
            addCriterion("fecha_validacion in", values, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionNotIn(List<Date> values) {
            addCriterion("fecha_validacion not in", values, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionBetween(Date value1, Date value2) {
            addCriterion("fecha_validacion between", value1, value2, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andFechaValidacionNotBetween(Date value1, Date value2) {
            addCriterion("fecha_validacion not between", value1, value2, "fechaValidacion");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorIsNull() {
            addCriterion("id_usuario_validador is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorIsNotNull() {
            addCriterion("id_usuario_validador is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorEqualTo(Long value) {
            addCriterion("id_usuario_validador =", value, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorNotEqualTo(Long value) {
            addCriterion("id_usuario_validador <>", value, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorGreaterThan(Long value) {
            addCriterion("id_usuario_validador >", value, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorGreaterThanOrEqualTo(Long value) {
            addCriterion("id_usuario_validador >=", value, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorLessThan(Long value) {
            addCriterion("id_usuario_validador <", value, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorLessThanOrEqualTo(Long value) {
            addCriterion("id_usuario_validador <=", value, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorIn(List<Long> values) {
            addCriterion("id_usuario_validador in", values, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorNotIn(List<Long> values) {
            addCriterion("id_usuario_validador not in", values, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorBetween(Long value1, Long value2) {
            addCriterion("id_usuario_validador between", value1, value2, "idUsuarioValidador");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioValidadorNotBetween(Long value1, Long value2) {
            addCriterion("id_usuario_validador not between", value1, value2, "idUsuarioValidador");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated do_not_delete_during_merge Tue May 30 10:37:46 CEST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}