package com.comerzzia.bricodepot.backoffice.persistence.devoluciones.validacion;

import com.comerzzia.bricodepot.backoffice.persistence.devoluciones.validacion.ValidacionDevolucionAlbaran;
import com.comerzzia.bricodepot.backoffice.persistence.devoluciones.validacion.ValidacionDevolucionAlbaranExample;
import com.comerzzia.bricodepot.backoffice.persistence.devoluciones.validacion.ValidacionDevolucionAlbaranKey;
import com.comerzzia.core.util.paginacion.PaginaResultados;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ValidacionDevolucionAlbaranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    long countByExample(ValidacionDevolucionAlbaranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int deleteByExample(ValidacionDevolucionAlbaranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int deleteByPrimaryKey(ValidacionDevolucionAlbaranKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int insert(ValidacionDevolucionAlbaran row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int insertSelective(ValidacionDevolucionAlbaran row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    List<ValidacionDevolucionAlbaran> selectByExample(ValidacionDevolucionAlbaranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    ValidacionDevolucionAlbaran selectByPrimaryKey(ValidacionDevolucionAlbaranKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int updateByExampleSelective(@Param("row") ValidacionDevolucionAlbaran row, @Param("example") ValidacionDevolucionAlbaranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int updateByExample(@Param("row") ValidacionDevolucionAlbaran row, @Param("example") ValidacionDevolucionAlbaranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int updateByPrimaryKeySelective(ValidacionDevolucionAlbaran row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_clie_albaranes_dev_tbl
     *
     * @mbg.generated Tue May 30 10:37:46 CEST 2023
     */
    int updateByPrimaryKey(ValidacionDevolucionAlbaran row);
    
    /* ==================== MÉTODOS PERSONALIZADOS ==================== */
    
    List<ValidacionDevolucionAlbaran> consultarPaginado(ParametrosBuscarValidacionesDevolucionAlbaran param);
}