package com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.sco.acumuladorventas;

import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.sco.acumuladorventas.AcumuladorVentas;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.sco.acumuladorventas.AcumuladorVentasExample;
import com.comerzzia.bricodepot.backoffice.persistence.albaranes.venta.sco.acumuladorventas.AcumuladorVentasKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcumuladorVentasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    long countByExample(AcumuladorVentasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int deleteByExample(AcumuladorVentasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int deleteByPrimaryKey(AcumuladorVentasKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int insert(AcumuladorVentas row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int insertSelective(AcumuladorVentas row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    List<AcumuladorVentas> selectByExample(AcumuladorVentasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    AcumuladorVentas selectByPrimaryKey(AcumuladorVentasKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int updateByExampleSelective(@Param("row") AcumuladorVentas row, @Param("example") AcumuladorVentasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int updateByExample(@Param("row") AcumuladorVentas row, @Param("example") AcumuladorVentasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int updateByPrimaryKeySelective(AcumuladorVentas row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_ventas_acum_sco_tbl
     *
     * @mbg.generated Mon Jan 22 11:01:02 CET 2024
     */
    int updateByPrimaryKey(AcumuladorVentas row);
}