package com.comerzzia.bricodepot.backoffice.persistence.general.tiendas.atcud;

import java.util.ArrayList;
import java.util.List;

public class AtcudMagentoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public AtcudMagentoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("UID_ACTIVIDAD is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("UID_ACTIVIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("UID_ACTIVIDAD >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("UID_ACTIVIDAD <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("UID_ACTIVIDAD <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("UID_ACTIVIDAD like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("UID_ACTIVIDAD not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("UID_ACTIVIDAD not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("UID_ACTIVIDAD not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNull() {
            addCriterion("CODALM is null");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNotNull() {
            addCriterion("CODALM is not null");
            return (Criteria) this;
        }

        public Criteria andCodalmEqualTo(String value) {
            addCriterion("CODALM =", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotEqualTo(String value) {
            addCriterion("CODALM <>", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThan(String value) {
            addCriterion("CODALM >", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThanOrEqualTo(String value) {
            addCriterion("CODALM >=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThan(String value) {
            addCriterion("CODALM <", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThanOrEqualTo(String value) {
            addCriterion("CODALM <=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLike(String value) {
            addCriterion("CODALM like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotLike(String value) {
            addCriterion("CODALM not like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmIn(List<String> values) {
            addCriterion("CODALM in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotIn(List<String> values) {
            addCriterion("CODALM not in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmBetween(String value1, String value2) {
            addCriterion("CODALM between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotBetween(String value1, String value2) {
            addCriterion("CODALM not between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andIdContadorIsNull() {
            addCriterion("ID_CONTADOR is null");
            return (Criteria) this;
        }

        public Criteria andIdContadorIsNotNull() {
            addCriterion("ID_CONTADOR is not null");
            return (Criteria) this;
        }

        public Criteria andIdContadorEqualTo(String value) {
            addCriterion("ID_CONTADOR =", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorNotEqualTo(String value) {
            addCriterion("ID_CONTADOR <>", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorGreaterThan(String value) {
            addCriterion("ID_CONTADOR >", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CONTADOR >=", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorLessThan(String value) {
            addCriterion("ID_CONTADOR <", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorLessThanOrEqualTo(String value) {
            addCriterion("ID_CONTADOR <=", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorLike(String value) {
            addCriterion("ID_CONTADOR like", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorNotLike(String value) {
            addCriterion("ID_CONTADOR not like", value, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorIn(List<String> values) {
            addCriterion("ID_CONTADOR in", values, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorNotIn(List<String> values) {
            addCriterion("ID_CONTADOR not in", values, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorBetween(String value1, String value2) {
            addCriterion("ID_CONTADOR between", value1, value2, "idContador");
            return (Criteria) this;
        }

        public Criteria andIdContadorNotBetween(String value1, String value2) {
            addCriterion("ID_CONTADOR not between", value1, value2, "idContador");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1IsNull() {
            addCriterion("MASCARA_DIVISOR1 is null");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1IsNotNull() {
            addCriterion("MASCARA_DIVISOR1 is not null");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1EqualTo(String value) {
            addCriterion("MASCARA_DIVISOR1 =", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1NotEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR1 <>", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1GreaterThan(String value) {
            addCriterion("MASCARA_DIVISOR1 >", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1GreaterThanOrEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR1 >=", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1LessThan(String value) {
            addCriterion("MASCARA_DIVISOR1 <", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1LessThanOrEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR1 <=", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1Like(String value) {
            addCriterion("MASCARA_DIVISOR1 like", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1NotLike(String value) {
            addCriterion("MASCARA_DIVISOR1 not like", value, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1In(List<String> values) {
            addCriterion("MASCARA_DIVISOR1 in", values, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1NotIn(List<String> values) {
            addCriterion("MASCARA_DIVISOR1 not in", values, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1Between(String value1, String value2) {
            addCriterion("MASCARA_DIVISOR1 between", value1, value2, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor1NotBetween(String value1, String value2) {
            addCriterion("MASCARA_DIVISOR1 not between", value1, value2, "mascaraDivisor1");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2IsNull() {
            addCriterion("MASCARA_DIVISOR2 is null");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2IsNotNull() {
            addCriterion("MASCARA_DIVISOR2 is not null");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2EqualTo(String value) {
            addCriterion("MASCARA_DIVISOR2 =", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2NotEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR2 <>", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2GreaterThan(String value) {
            addCriterion("MASCARA_DIVISOR2 >", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2GreaterThanOrEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR2 >=", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2LessThan(String value) {
            addCriterion("MASCARA_DIVISOR2 <", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2LessThanOrEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR2 <=", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2Like(String value) {
            addCriterion("MASCARA_DIVISOR2 like", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2NotLike(String value) {
            addCriterion("MASCARA_DIVISOR2 not like", value, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2In(List<String> values) {
            addCriterion("MASCARA_DIVISOR2 in", values, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2NotIn(List<String> values) {
            addCriterion("MASCARA_DIVISOR2 not in", values, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2Between(String value1, String value2) {
            addCriterion("MASCARA_DIVISOR2 between", value1, value2, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor2NotBetween(String value1, String value2) {
            addCriterion("MASCARA_DIVISOR2 not between", value1, value2, "mascaraDivisor2");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3IsNull() {
            addCriterion("MASCARA_DIVISOR3 is null");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3IsNotNull() {
            addCriterion("MASCARA_DIVISOR3 is not null");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3EqualTo(String value) {
            addCriterion("MASCARA_DIVISOR3 =", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3NotEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR3 <>", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3GreaterThan(String value) {
            addCriterion("MASCARA_DIVISOR3 >", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3GreaterThanOrEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR3 >=", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3LessThan(String value) {
            addCriterion("MASCARA_DIVISOR3 <", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3LessThanOrEqualTo(String value) {
            addCriterion("MASCARA_DIVISOR3 <=", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3Like(String value) {
            addCriterion("MASCARA_DIVISOR3 like", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3NotLike(String value) {
            addCriterion("MASCARA_DIVISOR3 not like", value, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3In(List<String> values) {
            addCriterion("MASCARA_DIVISOR3 in", values, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3NotIn(List<String> values) {
            addCriterion("MASCARA_DIVISOR3 not in", values, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3Between(String value1, String value2) {
            addCriterion("MASCARA_DIVISOR3 between", value1, value2, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andMascaraDivisor3NotBetween(String value1, String value2) {
            addCriterion("MASCARA_DIVISOR3 not between", value1, value2, "mascaraDivisor3");
            return (Criteria) this;
        }

        public Criteria andRangoIsNull() {
            addCriterion("RANGO is null");
            return (Criteria) this;
        }

        public Criteria andRangoIsNotNull() {
            addCriterion("RANGO is not null");
            return (Criteria) this;
        }

        public Criteria andRangoEqualTo(String value) {
            addCriterion("RANGO =", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoNotEqualTo(String value) {
            addCriterion("RANGO <>", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoGreaterThan(String value) {
            addCriterion("RANGO >", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoGreaterThanOrEqualTo(String value) {
            addCriterion("RANGO >=", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoLessThan(String value) {
            addCriterion("RANGO <", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoLessThanOrEqualTo(String value) {
            addCriterion("RANGO <=", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoLike(String value) {
            addCriterion("RANGO like", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoNotLike(String value) {
            addCriterion("RANGO not like", value, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoIn(List<String> values) {
            addCriterion("RANGO in", values, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoNotIn(List<String> values) {
            addCriterion("RANGO not in", values, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoBetween(String value1, String value2) {
            addCriterion("RANGO between", value1, value2, "rango");
            return (Criteria) this;
        }

        public Criteria andRangoNotBetween(String value1, String value2) {
            addCriterion("RANGO not between", value1, value2, "rango");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 20 10:12:36 CET 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}