package com.comerzzia.bricodepot.backoffice.persistence.general.tiendas.atcud;

import com.comerzzia.bricodepot.backoffice.persistence.general.tiendas.atcud.AtcudMagento;
import com.comerzzia.bricodepot.backoffice.persistence.general.tiendas.atcud.AtcudMagentoExample;
import com.comerzzia.bricodepot.backoffice.persistence.general.tiendas.atcud.AtcudMagentoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AtcudMagentoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    long countByExample(AtcudMagentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int deleteByExample(AtcudMagentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int deleteByPrimaryKey(AtcudMagentoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int insert(AtcudMagento row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int insertSelective(AtcudMagento row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    List<AtcudMagento> selectByExample(AtcudMagentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    AtcudMagento selectByPrimaryKey(AtcudMagentoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int updateByExampleSelective(@Param("row") AtcudMagento row, @Param("example") AtcudMagentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int updateByExample(@Param("row") AtcudMagento row, @Param("example") AtcudMagentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int updateByPrimaryKeySelective(AtcudMagento row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_almacenes_atcud_tbl
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    int updateByPrimaryKey(AtcudMagento row);
}