package com.comerzzia.bricodepot.backoffice.persistence.general.tiendas.atcud;

public class AtcudMagento extends AtcudMagentoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR1
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    private String mascaraDivisor1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR2
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    private String mascaraDivisor2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR3
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    private String mascaraDivisor3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_almacenes_atcud_tbl.RANGO
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    private String rango;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR1
     *
     * @return the value of x_almacenes_atcud_tbl.MASCARA_DIVISOR1
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public String getMascaraDivisor1() {
        return mascaraDivisor1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR1
     *
     * @param mascaraDivisor1 the value for x_almacenes_atcud_tbl.MASCARA_DIVISOR1
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void setMascaraDivisor1(String mascaraDivisor1) {
        this.mascaraDivisor1 = mascaraDivisor1 == null ? null : mascaraDivisor1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR2
     *
     * @return the value of x_almacenes_atcud_tbl.MASCARA_DIVISOR2
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public String getMascaraDivisor2() {
        return mascaraDivisor2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR2
     *
     * @param mascaraDivisor2 the value for x_almacenes_atcud_tbl.MASCARA_DIVISOR2
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void setMascaraDivisor2(String mascaraDivisor2) {
        this.mascaraDivisor2 = mascaraDivisor2 == null ? null : mascaraDivisor2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR3
     *
     * @return the value of x_almacenes_atcud_tbl.MASCARA_DIVISOR3
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public String getMascaraDivisor3() {
        return mascaraDivisor3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_almacenes_atcud_tbl.MASCARA_DIVISOR3
     *
     * @param mascaraDivisor3 the value for x_almacenes_atcud_tbl.MASCARA_DIVISOR3
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void setMascaraDivisor3(String mascaraDivisor3) {
        this.mascaraDivisor3 = mascaraDivisor3 == null ? null : mascaraDivisor3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_almacenes_atcud_tbl.RANGO
     *
     * @return the value of x_almacenes_atcud_tbl.RANGO
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public String getRango() {
        return rango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_almacenes_atcud_tbl.RANGO
     *
     * @param rango the value for x_almacenes_atcud_tbl.RANGO
     *
     * @mbg.generated Mon Nov 20 10:12:36 CET 2023
     */
    public void setRango(String rango) {
        this.rango = rango == null ? null : rango.trim();
    }
}