package com.comerzzia.bricodepot.backoffice.persistence.conversion;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ConversionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public ConversionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("uid_actividad is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("uid_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("uid_actividad =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("uid_actividad <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("uid_actividad >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("uid_actividad >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("uid_actividad <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("uid_actividad <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("uid_actividad like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("uid_actividad not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("uid_actividad in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("uid_actividad not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("uid_actividad between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("uid_actividad not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNull() {
            addCriterion("uid_ticket is null");
            return (Criteria) this;
        }

        public Criteria andUidTicketIsNotNull() {
            addCriterion("uid_ticket is not null");
            return (Criteria) this;
        }

        public Criteria andUidTicketEqualTo(String value) {
            addCriterion("uid_ticket =", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotEqualTo(String value) {
            addCriterion("uid_ticket <>", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThan(String value) {
            addCriterion("uid_ticket >", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketGreaterThanOrEqualTo(String value) {
            addCriterion("uid_ticket >=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThan(String value) {
            addCriterion("uid_ticket <", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLessThanOrEqualTo(String value) {
            addCriterion("uid_ticket <=", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketLike(String value) {
            addCriterion("uid_ticket like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotLike(String value) {
            addCriterion("uid_ticket not like", value, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketIn(List<String> values) {
            addCriterion("uid_ticket in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotIn(List<String> values) {
            addCriterion("uid_ticket not in", values, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketBetween(String value1, String value2) {
            addCriterion("uid_ticket between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andUidTicketNotBetween(String value1, String value2) {
            addCriterion("uid_ticket not between", value1, value2, "uidTicket");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("fecha is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("fecha is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterionForJDBCDate("fecha =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterionForJDBCDate("fecha <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterionForJDBCDate("fecha in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha not between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaIsNull() {
            addCriterion("uid_factura_completa is null");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaIsNotNull() {
            addCriterion("uid_factura_completa is not null");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaEqualTo(String value) {
            addCriterion("uid_factura_completa =", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaNotEqualTo(String value) {
            addCriterion("uid_factura_completa <>", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaGreaterThan(String value) {
            addCriterion("uid_factura_completa >", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaGreaterThanOrEqualTo(String value) {
            addCriterion("uid_factura_completa >=", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaLessThan(String value) {
            addCriterion("uid_factura_completa <", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaLessThanOrEqualTo(String value) {
            addCriterion("uid_factura_completa <=", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaLike(String value) {
            addCriterion("uid_factura_completa like", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaNotLike(String value) {
            addCriterion("uid_factura_completa not like", value, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaIn(List<String> values) {
            addCriterion("uid_factura_completa in", values, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaNotIn(List<String> values) {
            addCriterion("uid_factura_completa not in", values, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaBetween(String value1, String value2) {
            addCriterion("uid_factura_completa between", value1, value2, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andUidFacturaCompletaNotBetween(String value1, String value2) {
            addCriterion("uid_factura_completa not between", value1, value2, "uidFacturaCompleta");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaIsNull() {
            addCriterion("factura_transformada is null");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaIsNotNull() {
            addCriterion("factura_transformada is not null");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaEqualTo(String value) {
            addCriterion("factura_transformada =", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaNotEqualTo(String value) {
            addCriterion("factura_transformada <>", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaGreaterThan(String value) {
            addCriterion("factura_transformada >", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaGreaterThanOrEqualTo(String value) {
            addCriterion("factura_transformada >=", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaLessThan(String value) {
            addCriterion("factura_transformada <", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaLessThanOrEqualTo(String value) {
            addCriterion("factura_transformada <=", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaLike(String value) {
            addCriterion("factura_transformada like", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaNotLike(String value) {
            addCriterion("factura_transformada not like", value, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaIn(List<String> values) {
            addCriterion("factura_transformada in", values, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaNotIn(List<String> values) {
            addCriterion("factura_transformada not in", values, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaBetween(String value1, String value2) {
            addCriterion("factura_transformada between", value1, value2, "facturaTransformada");
            return (Criteria) this;
        }

        public Criteria andFacturaTransformadaNotBetween(String value1, String value2) {
            addCriterion("factura_transformada not between", value1, value2, "facturaTransformada");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 30 12:48:26 CET 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}