package com.comerzzia.bricodepot.backoffice.persistence.conversion;

public class Conversion extends ConversionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_tickets_tbl.factura_transformada
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    private String facturaTransformada;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_tickets_tbl.factura_transformada
     *
     * @return the value of x_tickets_tbl.factura_transformada
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public String getFacturaTransformada() {
        return facturaTransformada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_tickets_tbl.factura_transformada
     *
     * @param facturaTransformada the value for x_tickets_tbl.factura_transformada
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setFacturaTransformada(String facturaTransformada) {
        this.facturaTransformada = facturaTransformada == null ? null : facturaTransformada.trim();
    }
}