package com.comerzzia.bricodepot.backoffice.persistence.conversion;

import com.comerzzia.bricodepot.backoffice.persistence.conversion.Conversion;
import com.comerzzia.bricodepot.backoffice.persistence.conversion.ConversionExample;
import com.comerzzia.bricodepot.backoffice.persistence.conversion.ConversionKey;
import com.comerzzia.core.model.ventas.tickets.TicketBean;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    long countByExample(ConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int deleteByExample(ConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int deleteByPrimaryKey(ConversionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int insert(Conversion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int insertSelective(Conversion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    List<Conversion> selectByExample(ConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    Conversion selectByPrimaryKey(ConversionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int updateByExampleSelective(@Param("row") Conversion row, @Param("example") ConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int updateByExample(@Param("row") Conversion row, @Param("example") ConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int updateByPrimaryKeySelective(Conversion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_tickets_tbl
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    int updateByPrimaryKey(Conversion row);
    
    TicketBean selectByLocalizador(@Param("uidActividad")String uidActividad,@Param("locatorId")String locatorId);
}