package com.comerzzia.bricodepot.backoffice.persistence.conversion;

import java.util.Date;

public class ConversionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_tickets_tbl.uid_actividad
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    private String uidActividad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_tickets_tbl.uid_ticket
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    private String uidTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_tickets_tbl.fecha
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_tickets_tbl.uid_factura_completa
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    private String uidFacturaCompleta;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_tickets_tbl.uid_actividad
     *
     * @return the value of x_tickets_tbl.uid_actividad
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public String getUidActividad() {
        return uidActividad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_tickets_tbl.uid_actividad
     *
     * @param uidActividad the value for x_tickets_tbl.uid_actividad
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setUidActividad(String uidActividad) {
        this.uidActividad = uidActividad == null ? null : uidActividad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_tickets_tbl.uid_ticket
     *
     * @return the value of x_tickets_tbl.uid_ticket
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public String getUidTicket() {
        return uidTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_tickets_tbl.uid_ticket
     *
     * @param uidTicket the value for x_tickets_tbl.uid_ticket
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setUidTicket(String uidTicket) {
        this.uidTicket = uidTicket == null ? null : uidTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_tickets_tbl.fecha
     *
     * @return the value of x_tickets_tbl.fecha
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_tickets_tbl.fecha
     *
     * @param fecha the value for x_tickets_tbl.fecha
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_tickets_tbl.uid_factura_completa
     *
     * @return the value of x_tickets_tbl.uid_factura_completa
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public String getUidFacturaCompleta() {
        return uidFacturaCompleta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_tickets_tbl.uid_factura_completa
     *
     * @param uidFacturaCompleta the value for x_tickets_tbl.uid_factura_completa
     *
     * @mbg.generated Tue Jan 30 12:48:26 CET 2024
     */
    public void setUidFacturaCompleta(String uidFacturaCompleta) {
        this.uidFacturaCompleta = uidFacturaCompleta == null ? null : uidFacturaCompleta.trim();
    }
}