package com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CajasFicticiasExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public CajasFicticiasExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidActividadIsNull() {
            addCriterion("uid_actividad is null");
            return (Criteria) this;
        }

        public Criteria andUidActividadIsNotNull() {
            addCriterion("uid_actividad is not null");
            return (Criteria) this;
        }

        public Criteria andUidActividadEqualTo(String value) {
            addCriterion("uid_actividad =", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotEqualTo(String value) {
            addCriterion("uid_actividad <>", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThan(String value) {
            addCriterion("uid_actividad >", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadGreaterThanOrEqualTo(String value) {
            addCriterion("uid_actividad >=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThan(String value) {
            addCriterion("uid_actividad <", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLessThanOrEqualTo(String value) {
            addCriterion("uid_actividad <=", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadLike(String value) {
            addCriterion("uid_actividad like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotLike(String value) {
            addCriterion("uid_actividad not like", value, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadIn(List<String> values) {
            addCriterion("uid_actividad in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotIn(List<String> values) {
            addCriterion("uid_actividad not in", values, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadBetween(String value1, String value2) {
            addCriterion("uid_actividad between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andUidActividadNotBetween(String value1, String value2) {
            addCriterion("uid_actividad not between", value1, value2, "uidActividad");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNull() {
            addCriterion("codalm is null");
            return (Criteria) this;
        }

        public Criteria andCodalmIsNotNull() {
            addCriterion("codalm is not null");
            return (Criteria) this;
        }

        public Criteria andCodalmEqualTo(String value) {
            addCriterion("codalm =", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotEqualTo(String value) {
            addCriterion("codalm <>", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThan(String value) {
            addCriterion("codalm >", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmGreaterThanOrEqualTo(String value) {
            addCriterion("codalm >=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThan(String value) {
            addCriterion("codalm <", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLessThanOrEqualTo(String value) {
            addCriterion("codalm <=", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmLike(String value) {
            addCriterion("codalm like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotLike(String value) {
            addCriterion("codalm not like", value, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmIn(List<String> values) {
            addCriterion("codalm in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotIn(List<String> values) {
            addCriterion("codalm not in", values, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmBetween(String value1, String value2) {
            addCriterion("codalm between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodalmNotBetween(String value1, String value2) {
            addCriterion("codalm not between", value1, value2, "codalm");
            return (Criteria) this;
        }

        public Criteria andCodcajaIsNull() {
            addCriterion("codcaja is null");
            return (Criteria) this;
        }

        public Criteria andCodcajaIsNotNull() {
            addCriterion("codcaja is not null");
            return (Criteria) this;
        }

        public Criteria andCodcajaEqualTo(String value) {
            addCriterion("codcaja =", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotEqualTo(String value) {
            addCriterion("codcaja <>", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaGreaterThan(String value) {
            addCriterion("codcaja >", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaGreaterThanOrEqualTo(String value) {
            addCriterion("codcaja >=", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaLessThan(String value) {
            addCriterion("codcaja <", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaLessThanOrEqualTo(String value) {
            addCriterion("codcaja <=", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaLike(String value) {
            addCriterion("codcaja like", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotLike(String value) {
            addCriterion("codcaja not like", value, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaIn(List<String> values) {
            addCriterion("codcaja in", values, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotIn(List<String> values) {
            addCriterion("codcaja not in", values, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaBetween(String value1, String value2) {
            addCriterion("codcaja between", value1, value2, "codcaja");
            return (Criteria) this;
        }

        public Criteria andCodcajaNotBetween(String value1, String value2) {
            addCriterion("codcaja not between", value1, value2, "codcaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaIsNull() {
            addCriterion("uid_diario_caja is null");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaIsNotNull() {
            addCriterion("uid_diario_caja is not null");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaEqualTo(String value) {
            addCriterion("uid_diario_caja =", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotEqualTo(String value) {
            addCriterion("uid_diario_caja <>", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaGreaterThan(String value) {
            addCriterion("uid_diario_caja >", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaGreaterThanOrEqualTo(String value) {
            addCriterion("uid_diario_caja >=", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaLessThan(String value) {
            addCriterion("uid_diario_caja <", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaLessThanOrEqualTo(String value) {
            addCriterion("uid_diario_caja <=", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaLike(String value) {
            addCriterion("uid_diario_caja like", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotLike(String value) {
            addCriterion("uid_diario_caja not like", value, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaIn(List<String> values) {
            addCriterion("uid_diario_caja in", values, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotIn(List<String> values) {
            addCriterion("uid_diario_caja not in", values, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaBetween(String value1, String value2) {
            addCriterion("uid_diario_caja between", value1, value2, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andUidDiarioCajaNotBetween(String value1, String value2) {
            addCriterion("uid_diario_caja not between", value1, value2, "uidDiarioCaja");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaIsNull() {
            addCriterion("fecha_apertura is null");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaIsNotNull() {
            addCriterion("fecha_apertura is not null");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaEqualTo(Date value) {
            addCriterion("fecha_apertura =", value, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaNotEqualTo(Date value) {
            addCriterion("fecha_apertura <>", value, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaGreaterThan(Date value) {
            addCriterion("fecha_apertura >", value, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_apertura >=", value, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaLessThan(Date value) {
            addCriterion("fecha_apertura <", value, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaLessThanOrEqualTo(Date value) {
            addCriterion("fecha_apertura <=", value, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaIn(List<Date> values) {
            addCriterion("fecha_apertura in", values, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaNotIn(List<Date> values) {
            addCriterion("fecha_apertura not in", values, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaBetween(Date value1, Date value2) {
            addCriterion("fecha_apertura between", value1, value2, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaAperturaNotBetween(Date value1, Date value2) {
            addCriterion("fecha_apertura not between", value1, value2, "fechaApertura");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreIsNull() {
            addCriterion("fecha_ultimo_cierre is null");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreIsNotNull() {
            addCriterion("fecha_ultimo_cierre is not null");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreEqualTo(Date value) {
            addCriterion("fecha_ultimo_cierre =", value, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreNotEqualTo(Date value) {
            addCriterion("fecha_ultimo_cierre <>", value, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreGreaterThan(Date value) {
            addCriterion("fecha_ultimo_cierre >", value, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_ultimo_cierre >=", value, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreLessThan(Date value) {
            addCriterion("fecha_ultimo_cierre <", value, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreLessThanOrEqualTo(Date value) {
            addCriterion("fecha_ultimo_cierre <=", value, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreIn(List<Date> values) {
            addCriterion("fecha_ultimo_cierre in", values, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreNotIn(List<Date> values) {
            addCriterion("fecha_ultimo_cierre not in", values, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreBetween(Date value1, Date value2) {
            addCriterion("fecha_ultimo_cierre between", value1, value2, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaUltimoCierreNotBetween(Date value1, Date value2) {
            addCriterion("fecha_ultimo_cierre not between", value1, value2, "fechaUltimoCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreIsNull() {
            addCriterion("fecha_cierre is null");
            return (Criteria) this;
        }

        public Criteria andFechaCierreIsNotNull() {
            addCriterion("fecha_cierre is not null");
            return (Criteria) this;
        }

        public Criteria andFechaCierreEqualTo(Date value) {
            addCriterion("fecha_cierre =", value, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreNotEqualTo(Date value) {
            addCriterion("fecha_cierre <>", value, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreGreaterThan(Date value) {
            addCriterion("fecha_cierre >", value, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_cierre >=", value, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreLessThan(Date value) {
            addCriterion("fecha_cierre <", value, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreLessThanOrEqualTo(Date value) {
            addCriterion("fecha_cierre <=", value, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreIn(List<Date> values) {
            addCriterion("fecha_cierre in", values, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreNotIn(List<Date> values) {
            addCriterion("fecha_cierre not in", values, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreBetween(Date value1, Date value2) {
            addCriterion("fecha_cierre between", value1, value2, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andFechaCierreNotBetween(Date value1, Date value2) {
            addCriterion("fecha_cierre not between", value1, value2, "fechaCierre");
            return (Criteria) this;
        }

        public Criteria andSaldoIsNull() {
            addCriterion("saldo is null");
            return (Criteria) this;
        }

        public Criteria andSaldoIsNotNull() {
            addCriterion("saldo is not null");
            return (Criteria) this;
        }

        public Criteria andSaldoEqualTo(BigDecimal value) {
            addCriterion("saldo =", value, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoNotEqualTo(BigDecimal value) {
            addCriterion("saldo <>", value, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoGreaterThan(BigDecimal value) {
            addCriterion("saldo >", value, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("saldo >=", value, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoLessThan(BigDecimal value) {
            addCriterion("saldo <", value, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("saldo <=", value, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoIn(List<BigDecimal> values) {
            addCriterion("saldo in", values, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoNotIn(List<BigDecimal> values) {
            addCriterion("saldo not in", values, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("saldo between", value1, value2, "saldo");
            return (Criteria) this;
        }

        public Criteria andSaldoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("saldo not between", value1, value2, "saldo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 23 11:48:38 CET 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}