package com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.comerzzia.bricodepot.backoffice.persistence.ventas.cajas.detalles.CargosAbonosDto;
import com.comerzzia.core.omnichannel.engine.persistence.cajas.movimientos.CajaMovimientoBean;

public interface CajasFicticiasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    long countByExample(CajasFicticiasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int deleteByExample(CajasFicticiasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int deleteByPrimaryKey(CajasFicticiasKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int insert(CajasFicticias row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int insertSelective(CajasFicticias row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    List<CajasFicticias> selectByExample(CajasFicticiasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    CajasFicticias selectByPrimaryKey(CajasFicticiasKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int updateByExampleSelective(@Param("row") CajasFicticias row, @Param("example") CajasFicticiasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int updateByExample(@Param("row") CajasFicticias row, @Param("example") CajasFicticiasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int updateByPrimaryKeySelective(CajasFicticias row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_cajas_ficticias_tbl
     *
     * @mbg.generated Thu Nov 23 11:48:38 CET 2023
     */
    int updateByPrimaryKey(CajasFicticias row);
    
    List<CajaMovimientoBean> selectMovCaja(@Param("uidActividad")String uidActividad, @Param("codCaja")String codCaja, @Param("codconcepto_mov")String codconcepto_mov,@Param("codalmacen")String codalmacen);
    
    BigDecimal selectMaxLinea(@Param("uidActividad")String uidActividad,@Param("uidDiarioCaja")String uidDiarioCaja);
    
    CargosAbonosDto consultarCargosAbonosDet(@Param("uid_actividad")String uidActividad,@Param("uid_diario_caja") String uidDiarioCaja);
    
}