package com.comerzzia.bricodepot.backoffice.persistence.promociones.tipos;

import com.comerzzia.bricodepot.backoffice.persistence.promociones.tipos.TiposPromociones;
import com.comerzzia.bricodepot.backoffice.persistence.promociones.tipos.TiposPromocionesExample;
import com.comerzzia.bricodepot.backoffice.persistence.promociones.tipos.TiposPromocionesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TiposPromocionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    long countByExample(TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int deleteByExample(TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int deleteByPrimaryKey(TiposPromocionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int insert(TiposPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int insertSelective(TiposPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    List<TiposPromociones> selectByExampleWithBLOBs(TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    List<TiposPromociones> selectByExample(TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    TiposPromociones selectByPrimaryKey(TiposPromocionesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int updateByExampleSelective(@Param("row") TiposPromociones row, @Param("example") TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int updateByExampleWithBLOBs(@Param("row") TiposPromociones row, @Param("example") TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int updateByExample(@Param("row") TiposPromociones row, @Param("example") TiposPromocionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int updateByPrimaryKeySelective(TiposPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int updateByPrimaryKeyWithBLOBs(TiposPromociones row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_promociones_tipos_tbl
     *
     * @mbg.generated Wed Jan 03 12:06:22 CET 2024
     */
    int updateByPrimaryKey(TiposPromociones row);
}